set_property PACKAGE_PIN {F23} [get_ports {sys_clock_p}]
set_property PACKAGE_PIN {E23} [get_ports {sys_clock_n}]
set_property IOSTANDARD {LVDS} [get_ports {sys_clock_p}]
set_property IOSTANDARD {LVDS} [get_ports {sys_clock_n}]
set_property PACKAGE_PIN {K9} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_rxd}]
set_property PACKAGE_PIN {J9} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_txd}]
set_property PACKAGE_PIN {H7} [get_ports {sdio_spi_clk}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_clk}]
set_property PACKAGE_PIN {H8} [get_ports {sdio_spi_cs}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_cs}]
set_property PACKAGE_PIN {G7} [get_ports {sdio_spi_dat_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_0}]
set_property PACKAGE_PIN {L10} [get_ports {sdio_spi_dat_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_1}]
set_property PACKAGE_PIN {M10} [get_ports {sdio_spi_dat_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_2}]
set_property PACKAGE_PIN {G8} [get_ports {sdio_spi_dat_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_3}]
set_property PULLUP {TRUE} [get_ports {sdio_spi_cs}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_cs}]]]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_0}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_0}]]]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_1}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_1}]]]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_2}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_2}]]]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_3}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_3}]]]
set_property PACKAGE_PIN {H12} [get_ports {jtag_jtag_TCK}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TCK}]
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
set_property PACKAGE_PIN {E10} [get_ports {jtag_jtag_TMS}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TMS}]
set_property PACKAGE_PIN {D10} [get_ports {jtag_jtag_TDO}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDO}]
set_property PACKAGE_PIN {C11} [get_ports {jtag_jtag_TDI}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDI}]
set_property PACKAGE_PIN {D5} [get_ports {gpio_led_0_ls}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_led_0_ls}]
