// Generated by CIRCT firtool-1.75.0
module BundleBridgeNexus_UInt1_1(	// @[generators/diplomacy/diplomacy/src/diplomacy/bundlebridge/BundleBridgeNexus.scala:20:9]
  output auto_out	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire outputs_0 = 1'h0;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:78:32]
  assign auto_out = outputs_0;	// @[generators/diplomacy/diplomacy/src/diplomacy/bundlebridge/BundleBridgeNexus.scala:20:9, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:78:32]
endmodule

