// Generated by CIRCT firtool-1.75.0
module ClockSinkDomain_1(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  output        auto_gpio_0_int_xing_out_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_control_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_gpio_0_control_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_gpio_0_control_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_gpio_0_control_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_gpio_0_control_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [30:0] auto_gpio_0_control_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_gpio_0_control_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_gpio_0_control_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_gpio_0_control_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_control_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_gpio_0_control_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_gpio_0_control_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_gpio_0_control_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_gpio_0_control_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_gpio_0_io_out_pins_0_i_ival,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_oval,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_oe,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_ie,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_pue,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_ds,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_ds1,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_gpio_0_io_out_pins_0_o_poe,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  TLGPIO gpio_0 (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:295:51]
    .clock                               (auto_clock_in_clock),
    .reset                               (auto_clock_in_reset),
    .auto_int_xing_out_sync_0            (auto_gpio_0_int_xing_out_sync_0),
    .auto_control_xing_in_a_ready        (auto_gpio_0_control_xing_in_a_ready),
    .auto_control_xing_in_a_valid        (auto_gpio_0_control_xing_in_a_valid),
    .auto_control_xing_in_a_bits_opcode  (auto_gpio_0_control_xing_in_a_bits_opcode),
    .auto_control_xing_in_a_bits_size    (auto_gpio_0_control_xing_in_a_bits_size),
    .auto_control_xing_in_a_bits_source  (auto_gpio_0_control_xing_in_a_bits_source),
    .auto_control_xing_in_a_bits_address (auto_gpio_0_control_xing_in_a_bits_address),
    .auto_control_xing_in_a_bits_mask    (auto_gpio_0_control_xing_in_a_bits_mask),
    .auto_control_xing_in_a_bits_data    (auto_gpio_0_control_xing_in_a_bits_data),
    .auto_control_xing_in_d_ready        (auto_gpio_0_control_xing_in_d_ready),
    .auto_control_xing_in_d_valid        (auto_gpio_0_control_xing_in_d_valid),
    .auto_control_xing_in_d_bits_opcode  (auto_gpio_0_control_xing_in_d_bits_opcode),
    .auto_control_xing_in_d_bits_size    (auto_gpio_0_control_xing_in_d_bits_size),
    .auto_control_xing_in_d_bits_source  (auto_gpio_0_control_xing_in_d_bits_source),
    .auto_control_xing_in_d_bits_data    (auto_gpio_0_control_xing_in_d_bits_data),
    .auto_io_out_pins_0_i_ival           (auto_gpio_0_io_out_pins_0_i_ival),
    .auto_io_out_pins_0_o_oval           (auto_gpio_0_io_out_pins_0_o_oval),
    .auto_io_out_pins_0_o_oe             (auto_gpio_0_io_out_pins_0_o_oe),
    .auto_io_out_pins_0_o_ie             (auto_gpio_0_io_out_pins_0_o_ie),
    .auto_io_out_pins_0_o_pue            (auto_gpio_0_io_out_pins_0_o_pue),
    .auto_io_out_pins_0_o_ds             (auto_gpio_0_io_out_pins_0_o_ds),
    .auto_io_out_pins_0_o_ds1            (auto_gpio_0_io_out_pins_0_o_ds1),
    .auto_io_out_pins_0_o_poe            (auto_gpio_0_io_out_pins_0_o_poe)
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:295:51]
endmodule

