// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FPU(	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input  [31:0] io_inst,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [63:0] io_fromint_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [2:0]  io_fcsr_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_fcsr_flags_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [4:0]  io_fcsr_flags_bits,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [63:0] io_store_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [63:0] io_toint_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_ll_resp_val,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [2:0]  io_ll_resp_type,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [4:0]  io_ll_resp_tag,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [63:0] io_ll_resp_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_fcsr_rdy,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_nack_mem,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_illegal_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_killx,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_killm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_wen,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren1,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren2,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren3,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_sboard_set,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_sboard_clr,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [4:0]  io_sboard_clra	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
);

  wire         divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1036:34, :1046:{27,46}]
  wire [1:0]   divSqrt_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1038:66, :1042:25]
  wire [4:0]   divSqrt_flags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1038:66, :1041:23]
  wire [64:0]  divSqrt_wdata;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1038:66, :1040:23]
  wire         divSqrt_wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1038:66, :1039:21]
  wire         _divSqrt_2_io_inReady;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_2_io_outValid_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_2_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [64:0]  _divSqrt_2_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [4:0]   _divSqrt_2_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_1_io_inReady;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_1_io_outValid_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_1_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [32:0]  _divSqrt_1_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [4:0]   _divSqrt_1_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_io_inReady;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_io_outValid_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire         _divSqrt_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [16:0]  _divSqrt_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [4:0]   _divSqrt_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  wire [64:0]  _hfma_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:920:28]
  wire [4:0]   _hfma_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:920:28]
  wire [64:0]  _dfma_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:914:28]
  wire [4:0]   _dfma_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:914:28]
  wire [64:0]  _fpmu_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:892:20]
  wire [4:0]   _fpmu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:892:20]
  wire [64:0]  _ifpu_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:887:20]
  wire [4:0]   _ifpu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:887:20]
  wire [2:0]   _fpiu_io_out_bits_in_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  wire [64:0]  _fpiu_io_out_bits_in_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  wire [64:0]  _fpiu_io_out_bits_in_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  wire         _fpiu_io_out_bits_lt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  wire [4:0]   _fpiu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  wire [64:0]  _sfma_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:873:20]
  wire [4:0]   _sfma_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:873:20]
  wire [64:0]  _regfile_ext_R0_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
  wire [64:0]  _regfile_ext_R1_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
  wire [64:0]  _regfile_ext_R2_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
  wire         _fp_decoder_io_sigs_ren1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_swap12;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire [1:0]   _fp_decoder_io_sigs_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire [1:0]   _fp_decoder_io_sigs_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire         _fp_decoder_io_sigs_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  reg          ex_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29]
  reg  [31:0]  ex_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg          ex_reg_ctrl_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg  [1:0]   ex_reg_ctrl_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg  [1:0]   ex_reg_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg          ex_reg_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
  reg  [4:0]   ex_ra_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
  reg  [4:0]   ex_ra_1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
  reg  [4:0]   ex_ra_2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
  reg          load_wb;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:774:24]
  reg  [1:0]   load_wb_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:775:34]
  reg  [63:0]  load_wb_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:776:31]
  reg  [4:0]   load_wb_tag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:777:30]
  reg          mem_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30]
  reg  [31:0]  mem_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:31]
  reg          wb_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:793:29]
  reg  [1:0]   mem_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          mem_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
  reg          wb_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:803:26]
  wire [63:0]  _wdata_T_6 = ((&load_wb_typeTag) | load_wb_typeTag == 2'h2 ? 64'h0 : load_wb_typeTag == 2'h1 ? 64'hFFFFFFFF00000000 : 64'hFFFFFFFFFFFF0000) | load_wb_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :775:34, :776:31, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire         wdata_rawIn_isZeroExpIn = _wdata_T_6[62:52] == 11'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [5:0]   wdata_rawIn_normDist = _wdata_T_6[51] ? 6'h0 : _wdata_T_6[50] ? 6'h1 : _wdata_T_6[49] ? 6'h2 : _wdata_T_6[48] ? 6'h3 : _wdata_T_6[47] ? 6'h4 : _wdata_T_6[46] ? 6'h5 : _wdata_T_6[45] ? 6'h6 : _wdata_T_6[44] ? 6'h7 : _wdata_T_6[43] ? 6'h8 : _wdata_T_6[42] ? 6'h9 : _wdata_T_6[41] ? 6'hA : _wdata_T_6[40] ? 6'hB : _wdata_T_6[39] ? 6'hC : _wdata_T_6[38] ? 6'hD : _wdata_T_6[37] ? 6'hE : _wdata_T_6[36] ? 6'hF : _wdata_T_6[35] ? 6'h10 : _wdata_T_6[34] ? 6'h11 : _wdata_T_6[33] ? 6'h12 : _wdata_T_6[32] ? 6'h13 : _wdata_T_6[31] ? 6'h14 : _wdata_T_6[30] ? 6'h15 : _wdata_T_6[29] ? 6'h16 : _wdata_T_6[28] ? 6'h17 : _wdata_T_6[27] ? 6'h18 : _wdata_T_6[26] ? 6'h19 : _wdata_T_6[25] ? 6'h1A : _wdata_T_6[24] ? 6'h1B : _wdata_T_6[23] ? 6'h1C : _wdata_T_6[22] ? 6'h1D : _wdata_T_6[21] ? 6'h1E : _wdata_T_6[20] ? 6'h1F : _wdata_T_6[19] ? 6'h20 : _wdata_T_6[18] ? 6'h21 : _wdata_T_6[17] ? 6'h22 : _wdata_T_6[16] ? 6'h23 : _wdata_T_6[15] ? 6'h24 : _wdata_T_6[14] ? 6'h25 : _wdata_T_6[13] ? 6'h26 : _wdata_T_6[12] ? 6'h27 : _wdata_T_6[11] ? 6'h28 : _wdata_T_6[10] ? 6'h29 : _wdata_T_6[9] ? 6'h2A : _wdata_T_6[8] ? 6'h2B : _wdata_T_6[7] ? 6'h2C : _wdata_T_6[6] ? 6'h2D : _wdata_T_6[5] ? 6'h2E : _wdata_T_6[4] ? 6'h2F : _wdata_T_6[3] ? 6'h30 : _wdata_T_6[2] ? 6'h31 : {5'h19, ~(_wdata_T_6[1])};	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [114:0] _wdata_rawIn_subnormFract_T = {63'h0, _wdata_T_6[51:0]} << wdata_rawIn_normDist;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [11:0]  _wdata_rawIn_adjustedExp_T_4 = (wdata_rawIn_isZeroExpIn ? {6'h3F, ~wdata_rawIn_normDist} : {1'h0, _wdata_T_6[62:52]}) + {10'h100, wdata_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [51:0]  _wdata_rawIn_out_sig_T_2 = wdata_rawIn_isZeroExpIn ? {_wdata_rawIn_subnormFract_T[50:0], 1'h0} : _wdata_T_6[51:0];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :52:{33,46,64}, :70:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [2:0]   _wdata_T_8 = wdata_rawIn_isZeroExpIn & ~(|(_wdata_T_6[51:0])) ? 3'h0 : _wdata_rawIn_adjustedExp_T_4[11:9];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire         _GEN = _wdata_T_8[0] | (&(_wdata_rawIn_adjustedExp_T_4[11:10])) & (|(_wdata_T_6[51:0]));	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :49:34, :57:9, :61:{32,57}, :64:28, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire         wdata_rawIn_isZeroExpIn_1 = _wdata_T_6[30:23] == 8'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [4:0]   wdata_rawIn_normDist_1 = _wdata_T_6[22] ? 5'h0 : _wdata_T_6[21] ? 5'h1 : _wdata_T_6[20] ? 5'h2 : _wdata_T_6[19] ? 5'h3 : _wdata_T_6[18] ? 5'h4 : _wdata_T_6[17] ? 5'h5 : _wdata_T_6[16] ? 5'h6 : _wdata_T_6[15] ? 5'h7 : _wdata_T_6[14] ? 5'h8 : _wdata_T_6[13] ? 5'h9 : _wdata_T_6[12] ? 5'hA : _wdata_T_6[11] ? 5'hB : _wdata_T_6[10] ? 5'hC : _wdata_T_6[9] ? 5'hD : _wdata_T_6[8] ? 5'hE : _wdata_T_6[7] ? 5'hF : _wdata_T_6[6] ? 5'h10 : _wdata_T_6[5] ? 5'h11 : _wdata_T_6[4] ? 5'h12 : _wdata_T_6[3] ? 5'h13 : _wdata_T_6[2] ? 5'h14 : _wdata_T_6[1] ? 5'h15 : 5'h16;	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [53:0]  _wdata_rawIn_subnormFract_T_2 = {31'h0, _wdata_T_6[22:0]} << wdata_rawIn_normDist_1;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [8:0]   _wdata_rawIn_adjustedExp_T_9 = (wdata_rawIn_isZeroExpIn_1 ? {4'hF, ~wdata_rawIn_normDist_1} : {1'h0, _wdata_T_6[30:23]}) + {7'h20, wdata_rawIn_isZeroExpIn_1 ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [22:0]  _wdata_rawIn_out_sig_T_6 = wdata_rawIn_isZeroExpIn_1 ? {_wdata_rawIn_subnormFract_T_2[21:0], 1'h0} : _wdata_T_6[22:0];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :52:{33,46,64}, :70:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [2:0]   _wdata_T_17 = wdata_rawIn_isZeroExpIn_1 & ~(|(_wdata_T_6[22:0])) ? 3'h0 : _wdata_rawIn_adjustedExp_T_9[8:6];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire         _GEN_0 = _wdata_T_17[0] | (&(_wdata_rawIn_adjustedExp_T_9[8:7])) & (|(_wdata_T_6[22:0]));	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :49:34, :57:9, :61:{32,57}, :64:28, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire         wdata_rawIn_isZeroExpIn_2 = _wdata_T_6[14:10] == 5'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [3:0]   wdata_rawIn_normDist_2 = _wdata_T_6[9] ? 4'h0 : _wdata_T_6[8] ? 4'h1 : _wdata_T_6[7] ? 4'h2 : _wdata_T_6[6] ? 4'h3 : _wdata_T_6[5] ? 4'h4 : _wdata_T_6[4] ? 4'h5 : _wdata_T_6[3] ? 4'h6 : _wdata_T_6[2] ? 4'h7 : {3'h4, ~(_wdata_T_6[1])};	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :735:7, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [24:0]  _wdata_rawIn_subnormFract_T_4 = {15'h0, _wdata_T_6[9:0]} << wdata_rawIn_normDist_2;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [5:0]   _wdata_rawIn_adjustedExp_T_14 = (wdata_rawIn_isZeroExpIn_2 ? {2'h3, ~wdata_rawIn_normDist_2} : {1'h0, _wdata_T_6[14:10]}) + {4'h4, wdata_rawIn_isZeroExpIn_2 ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :735:7, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [2:0]   _wdata_T_26 = wdata_rawIn_isZeroExpIn_2 & ~(|(_wdata_T_6[9:0])) ? 3'h0 : _wdata_rawIn_adjustedExp_T_14[5:3];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [60:0]  _GEN_1 = (&{_wdata_T_8[2:1], _GEN}) ? {&(_wdata_rawIn_out_sig_T_2[51:32]), _wdata_rawIn_adjustedExp_T_4[7:1], _wdata_T_17[2], _wdata_rawIn_out_sig_T_2[51:32], _wdata_T_6[31], _wdata_T_17[1], _GEN_0, (&{_wdata_T_17[2:1], _GEN_0}) ? {&(_wdata_rawIn_out_sig_T_6[22:16]), _wdata_rawIn_adjustedExp_T_9[4:1], _wdata_T_26[2], _wdata_rawIn_out_sig_T_6[22:16], _wdata_T_6[15], _wdata_T_26[1], _wdata_T_26[0] | (&(_wdata_rawIn_adjustedExp_T_14[5:4])) & (|(_wdata_T_6[9:0])), _wdata_rawIn_adjustedExp_T_14[2:0], wdata_rawIn_isZeroExpIn_2 ? {_wdata_rawIn_subnormFract_T_4[8:0], 1'h0} : _wdata_T_6[9:0]} : {_wdata_rawIn_adjustedExp_T_9[5:0], _wdata_rawIn_out_sig_T_6}} : {_wdata_rawIn_adjustedExp_T_4[8:0], _wdata_rawIn_out_sig_T_2};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}, generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :336:26, :338:{8,42}, :339:8, :340:8, :343:8, :344:8, :431:23]
  wire [2:0]   ex_rm = (&(ex_reg_inst[14:12])) ? io_fcsr_rm : ex_reg_inst[14:12];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :846:{18,30,38}]
  wire         _hfma_io_in_valid_T = ex_reg_valid & ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29, :770:30, :874:33]
  wire         _write_port_busy_T_20 = ex_reg_ctrl_typeTagOut == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :874:70]
  wire [2:0]   fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_expCode = {_regfile_ext_R2_data[23], _regfile_ext_R2_data[14:13]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :819:20]
  wire [11:0]  _fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_commonCase_T_2 = {6'h0, _regfile_ext_R2_data[23], _regfile_ext_R2_data[14:10]} + 12'h7E0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :819:20]
  wire [2:0]   fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode = {_regfile_ext_R2_data[52], _regfile_ext_R2_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :819:20]
  wire [11:0]  _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2 = {3'h0, _regfile_ext_R2_data[52], _regfile_ext_R2_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :819:20]
  wire         _fpiu_io_in_bits_req_in3_T_6 = ex_reg_ctrl_typeTagIn == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, generators/rocket-chip/src/main/scala/util/package.scala:39:86]
  wire         _GEN_2 = (&ex_reg_ctrl_typeTagIn) | ex_reg_ctrl_typeTagIn == 2'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [64:0]  fpmu_io_in_bits_in1 = _GEN_2 | (_fpiu_io_in_bits_req_in3_T_6 | (&{_regfile_ext_R2_data[31], _regfile_ext_R2_data[52], _regfile_ext_R2_data[30:28]})) & (&(_regfile_ext_R2_data[64:60])) ? (_GEN_2 ? _regfile_ext_R2_data : _fpiu_io_in_bits_req_in3_T_6 ? {_regfile_ext_R2_data[31], fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R2_data[52], _regfile_ext_R2_data[30:29], _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2, _regfile_ext_R2_data[22:0], 29'h0} : {_regfile_ext_R2_data[15], fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R2_data[23], _regfile_ext_R2_data[14:13], _fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in1_prev_prev_prev_prev_expOut_commonCase_T_2, _regfile_ext_R2_data[9:0], 42'h0}) : 65'hE008000000000000;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :819:20, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [2:0]   fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_expCode = {_regfile_ext_R1_data[23], _regfile_ext_R1_data[14:13]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :819:20]
  wire [11:0]  _fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_commonCase_T_2 = {6'h0, _regfile_ext_R1_data[23], _regfile_ext_R1_data[14:10]} + 12'h7E0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :819:20]
  wire [2:0]   fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode = {_regfile_ext_R1_data[52], _regfile_ext_R1_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :819:20]
  wire [11:0]  _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2 = {3'h0, _regfile_ext_R1_data[52], _regfile_ext_R1_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :819:20]
  wire [64:0]  fpmu_io_in_bits_in2 = _GEN_2 | (_fpiu_io_in_bits_req_in3_T_6 | (&{_regfile_ext_R1_data[31], _regfile_ext_R1_data[52], _regfile_ext_R1_data[30:28]})) & (&(_regfile_ext_R1_data[64:60])) ? (_GEN_2 ? _regfile_ext_R1_data : _fpiu_io_in_bits_req_in3_T_6 ? {_regfile_ext_R1_data[31], fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R1_data[52], _regfile_ext_R1_data[30:29], _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2, _regfile_ext_R1_data[22:0], 29'h0} : {_regfile_ext_R1_data[15], fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R1_data[23], _regfile_ext_R1_data[14:13], _fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in2_prev_prev_prev_prev_expOut_commonCase_T_2, _regfile_ext_R1_data[9:0], 42'h0}) : 65'hE008000000000000;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :819:20, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  reg  [4:0]   divSqrt_waddr;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:899:26]
  wire         _write_port_busy_T_26 = ex_reg_ctrl_typeTagOut == 2'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :921:78]
  wire         _divSqrt_io_inValid_T_2 = mem_ctrl_typeTagOut == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :912:72]
  wire         _divSqrt_io_inValid_T_4 = mem_ctrl_typeTagOut == 2'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :917:78]
  wire         _divSqrt_io_inValid_T = mem_ctrl_typeTagOut == 2'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :923:78]
  reg  [2:0]   wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20]
  reg  [4:0]   wbInfo_0_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [1:0]   wbInfo_0_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg          wbInfo_0_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [2:0]   wbInfo_0_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [4:0]   wbInfo_1_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [1:0]   wbInfo_1_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg          wbInfo_1_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [2:0]   wbInfo_1_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [4:0]   wbInfo_2_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [1:0]   wbInfo_2_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg          wbInfo_2_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg  [2:0]   wbInfo_2_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
  reg          write_port_busy;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:943:34]
  wire [4:0]   waddr = divSqrt_wen ? divSqrt_waddr : wbInfo_0_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:899:26, :941:19, :964:18, :1038:66, :1039:21]
  wire [1:0]   wtypeTag = divSqrt_wen ? divSqrt_typeTag : wbInfo_0_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, :966:21, :1038:66, :1039:21, :1042:25]
  wire         _wexc_T = wbInfo_0_pipeid == 3'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, generators/rocket-chip/src/main/scala/util/package.scala:39:86]
  wire         _wexc_T_2 = wbInfo_0_pipeid == 3'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, generators/rocket-chip/src/main/scala/util/package.scala:39:86]
  wire         _io_sboard_clr_T_3 = wbInfo_0_pipeid == 3'h3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, generators/rocket-chip/src/main/scala/util/package.scala:39:86]
  wire         _GEN_3 = (&wbInfo_0_pipeid) | wbInfo_0_pipeid == 3'h6 | wbInfo_0_pipeid == 3'h5 | wbInfo_0_pipeid == 3'h4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [64:0]  _wdata_T_53 = divSqrt_wen ? divSqrt_wdata : _GEN_3 ? _hfma_io_out_bits_data : _io_sboard_clr_T_3 ? _dfma_io_out_bits_data : _wexc_T_2 ? _sfma_io_out_bits_data : _wexc_T ? _ifpu_io_out_bits_data : _fpmu_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:873:20, :887:20, :892:20, :914:28, :920:28, :967:22, :1038:66, :1039:21, :1040:23, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [64:0]  wdata_1 = (&wtypeTag) | wtypeTag == 2'h2 ? _wdata_T_53 : wtypeTag == 2'h1 ? {12'hFFF, _wdata_T_53[31], 20'hFFFFF, _wdata_T_53[32], _wdata_T_53[30:0]} : {41'h1FFFFFFFFFF, _wdata_T_53[15], 7'h7F, _wdata_T_53[16], _wdata_T_53[14:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:336:26, :340:8, :342:8, :343:8, :398:14, :966:21, :967:22, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire         _GEN_4 = ~wbInfo_0_cp & wen[0] | divSqrt_wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :941:19, :969:{10,24,30,35}, :1038:66, :1039:21]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
      if (load_wb & ~reset & ~(({_wdata_T_6[63], _wdata_T_8[2:1], _GEN, _GEN_1[60]} != 5'h1F | {_GEN_1[52], _GEN_1[30:29]} != 3'h7 | _GEN_1[28] == (&(_GEN_1[22:16]))) & ({_wdata_T_8[2:1], _GEN} != 3'h7 | _GEN_1[60] == (&(_GEN_1[51:32]))))) begin	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :332:{49,84}, :344:8, :382:10, :384:33, :385:{31,35,55,60,96}, :386:14, :431:23, :774:24, :823:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
          $error("Assertion failed\n    at FPU.scala:823 assert(consistent(wdata))\n");	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:823:11]
      end
      if (_GEN_4 & ~reset & ~((wdata_1[64:60] != 5'h1F | {wdata_1[52], wdata_1[30:29]} != 3'h7 | wdata_1[28] == (&(wdata_1[22:16]))) & (wdata_1[63:61] != 3'h7 | wdata_1[60] == (&(wdata_1[51:32]))))) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :332:{49,84}, :382:10, :384:33, :385:{31,35,55,60,96}, :386:14, :823:11, :969:35, :970:11, generators/rocket-chip/src/main/scala/util/package.scala:39:76]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:970:11]
          $error("Assertion failed\n    at FPU.scala:970 assert(consistent(wdata))\n");	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:970:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:970:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:970:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire         wb_toint_valid = wb_reg_valid & wb_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:793:29, :803:26, :994:37]
  reg  [4:0]   wb_toint_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:995:31]
  wire         _divSqrt_inValid_T = mem_ctrl_div | mem_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :1002:47]
  wire         io_nack_mem_0 = write_port_busy | _divSqrt_inValid_T & (|wen) | divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :943:34, :1002:{47,65,72}, :1004:{35,62}, :1036:34, :1046:{27,46}]
  reg          io_sboard_set_REG;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1007:59]
  wire         divSqrt_inValid = mem_reg_valid & _divSqrt_inValid_T & ~divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30, :992:57, :1002:47, :1015:{41,76}, :1036:34, :1046:{27,46}]
  reg          divSqrt_killed;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1016:33]
  wire [5:0]   _divSqrt_io_a_expOut_commonCase_T = _fpiu_io_out_bits_in_in1[57:52] - 6'h20;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :877:20]
  wire [5:0]   _divSqrt_io_b_expOut_commonCase_T = _fpiu_io_out_bits_in_in2[57:52] - 6'h20;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :877:20]
  wire [8:0]   _divSqrt_io_a_expOut_commonCase_T_3 = _fpiu_io_out_bits_in_in1[60:52] - 9'h100;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :877:20]
  wire [8:0]   _divSqrt_io_b_expOut_commonCase_T_3 = _fpiu_io_out_bits_in_in2[60:52] - 9'h100;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :877:20]
  wire         _GEN_5 = _divSqrt_1_io_outValid_div | _divSqrt_1_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55, :1038:37]
  wire         _GEN_6 = _divSqrt_2_io_outValid_div | _divSqrt_2_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55, :1038:37]
  assign divSqrt_wen = _GEN_6 ? ~divSqrt_killed : _GEN_5 ? ~divSqrt_killed : (_divSqrt_io_outValid_div | _divSqrt_io_outValid_sqrt) & ~divSqrt_killed;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:897:32, :1016:33, :1028:55, :1038:{37,66}, :1039:{21,24}]
  assign divSqrt_wdata = _GEN_6 ? ({65{_divSqrt_2_io_out[63:61] != 3'h7}} | 65'h1EFEFFFFFFFFFFFFF) & _divSqrt_2_io_out : _GEN_5 ? {32'h0, ({33{_divSqrt_1_io_out[31:29] != 3'h7}} | 33'h1EF7FFFFF) & _divSqrt_1_io_out} : {48'h0, _divSqrt_io_out};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :414:10, :853:13, :1028:55, :1038:{37,66}, :1040:23]
  assign divSqrt_flags = _GEN_6 ? _divSqrt_2_io_exceptionFlags : _GEN_5 ? _divSqrt_1_io_exceptionFlags : _divSqrt_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55, :1038:{37,66}, :1041:23]
  assign divSqrt_typeTag = _GEN_6 ? 2'h2 : {1'h0, _GEN_5};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1038:{37,66}, :1042:25]
  assign divSqrt_inFlight = ~divSqrt_killed & (~_divSqrt_2_io_inReady | ~_divSqrt_1_io_inReady | ~_divSqrt_io_inReady);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1016:33, :1028:55, :1036:{13,34,53}, :1046:{27,46}]
  wire         _killm_T = io_killm | io_nack_mem_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:786:25, :1004:{35,62}]
  wire         _GEN_7 = ex_reg_ctrl_fastpipe | ex_reg_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :927:72]
  wire         _memLatencyMask_T_6 = mem_ctrl_fma & _divSqrt_io_inValid_T_4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :917:{62,78}]
  wire         _memLatencyMask_T_11 = mem_ctrl_fastpipe | mem_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :927:72]
  wire         _GEN_8 = mem_ctrl_fma & _divSqrt_io_inValid_T_2 | mem_ctrl_fma & _divSqrt_io_inValid_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :912:{56,72}, :923:{62,78}, :927:72]
  wire         mem_wen = mem_reg_valid & (mem_ctrl_fma | mem_ctrl_fastpipe | mem_ctrl_fromint);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30, :802:27, :942:{31,48,69}]
  wire         _GEN_9 = mem_wen & ~write_port_busy & _memLatencyMask_T_11;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:927:72, :942:31, :943:34, :947:21, :950:18, :955:{13,30,52}, :956:22]
  wire         _GEN_10 = mem_wen & ~write_port_busy & _GEN_8;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:927:72, :942:31, :943:34, :947:21, :950:18, :955:{13,30,52}, :956:22]
  wire         _GEN_11 = mem_wen & ~write_port_busy & _memLatencyMask_T_6;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:917:62, :941:19, :942:31, :943:34, :950:18, :955:{13,30,52}, :956:22]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      ex_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29]
      mem_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30]
      wb_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:793:29]
      wen <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20]
      divSqrt_killed <= 1'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1016:33]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      ex_reg_valid <= io_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29]
      mem_reg_valid <= ex_reg_valid & ~(io_killx | mem_reg_valid & _killm_T);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29, :785:30, :786:25, :790:{24,41}, :791:{33,36}]
      wb_reg_valid <= mem_reg_valid & ~_killm_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30, :786:25, :793:{29,44,48}]
      wen <= mem_wen & ~_killm_T ? {_memLatencyMask_T_6, wen[2] | _GEN_8, wen[1] | _memLatencyMask_T_11} : {1'h0, wen[2:1]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:786:25, :793:48, :917:62, :927:72, :940:20, :942:31, :947:14, :949:{7,14}, :950:18, :951:19, :952:{11,23}]
      divSqrt_killed <= divSqrt_inValid & _killm_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:786:25, :1015:{41,76}, :1016:{33,50}]
    end
    if (io_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
      ex_reg_inst <= io_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
      ex_reg_ctrl_ren2 <= _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_ren3 <= _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_swap23 <= _fp_decoder_io_sigs_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_typeTagIn <= _fp_decoder_io_sigs_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_typeTagOut <= _fp_decoder_io_sigs_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_fromint <= _fp_decoder_io_sigs_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_toint <= _fp_decoder_io_sigs_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_fastpipe <= _fp_decoder_io_sigs_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_fma <= _fp_decoder_io_sigs_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_div <= _fp_decoder_io_sigs_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_sqrt <= _fp_decoder_io_sigs_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_wflags <= _fp_decoder_io_sigs_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      ex_reg_ctrl_vec <= _fp_decoder_io_sigs_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:30]
      if (_fp_decoder_io_sigs_ren2 & _fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :835:25, :839:25, :840:{29,40}]
        ex_ra_0 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :840:50]
      else if (_fp_decoder_io_sigs_ren1 & ~_fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :771:31, :835:25, :836:{13,30,41}]
        ex_ra_0 <= io_inst[19:15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :836:51]
      if (_fp_decoder_io_sigs_ren2 & ~_fp_decoder_io_sigs_swap12 & ~_fp_decoder_io_sigs_swap23)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :835:25, :836:13, :839:25, :842:{29,32,49,60}]
        ex_ra_1 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :842:70]
      else if (_fp_decoder_io_sigs_ren1 & _fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :771:31, :835:25, :837:{29,40}]
        ex_ra_1 <= io_inst[19:15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :837:50]
      if (_fp_decoder_io_sigs_ren3)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
        ex_ra_2 <= io_inst[31:27];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :844:46]
      else if (_fp_decoder_io_sigs_ren2 & _fp_decoder_io_sigs_swap23)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :771:31, :839:25, :841:{29,40}]
        ex_ra_2 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31, :841:50]
    end
    load_wb <= io_ll_resp_val;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:774:24]
    if (io_ll_resp_val) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
      load_wb_typeTag <= io_ll_resp_type[1:0] - 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:775:{34,50,56}]
      load_wb_data <= io_ll_resp_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:776:31]
      load_wb_tag <= io_ll_resp_tag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:777:30]
    end
    if (ex_reg_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29]
      mem_reg_inst <= ex_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :792:31]
      mem_ctrl_typeTagOut <= ex_reg_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_fromint <= ex_reg_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_toint <= ex_reg_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_fastpipe <= ex_reg_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_fma <= ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_div <= ex_reg_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_sqrt <= ex_reg_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_wflags <= ex_reg_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      mem_ctrl_vec <= ex_reg_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :802:27]
      write_port_busy <= |{mem_wen & (|({ex_reg_ctrl_fma & _write_port_busy_T_20 | ex_reg_ctrl_fma & _write_port_busy_T_26, _GEN_7} & {_memLatencyMask_T_6, _GEN_8})), _GEN_7 & wen[2]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :874:70, :912:56, :917:62, :921:78, :923:62, :927:72, :940:20, :942:31, :943:{34,43,62,89,93,101,128}]
    end
    if (mem_reg_valid)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:30]
      wb_ctrl_toint <= mem_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :803:26]
    if (divSqrt_inValid)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1015:{41,76}]
      divSqrt_waddr <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:31, :899:26, :1018:36]
    if (_GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:947:21, :950:18, :955:{30,52}, :956:22]
      wbInfo_0_rd <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:31, :941:19, :959:37]
      wbInfo_0_typeTag <= mem_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :941:19]
      wbInfo_0_pipeid <= {mem_ctrl_fma & _divSqrt_io_inValid_T, {mem_ctrl_fma & _divSqrt_io_inValid_T_2, mem_ctrl_fromint} | {2{mem_ctrl_fma & _divSqrt_io_inValid_T_4}}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :912:{56,72}, :917:{62,78}, :923:{62,78}, :929:{63,100}, :941:19]
    end
    else if (wen[1]) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :947:14]
      wbInfo_0_rd <= wbInfo_1_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
      wbInfo_0_typeTag <= wbInfo_1_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
      wbInfo_0_pipeid <= wbInfo_1_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
    end
    wbInfo_0_cp <= ~_GEN_9 & (wen[1] ? wbInfo_1_cp : wbInfo_0_cp);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :941:19, :947:{14,21,33}, :950:18, :955:{30,52}, :956:22]
    if (_GEN_10) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:947:21, :950:18, :955:{30,52}, :956:22]
      wbInfo_1_rd <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:31, :941:19, :959:37]
      wbInfo_1_typeTag <= mem_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :941:19]
      wbInfo_1_pipeid <= {mem_ctrl_fma & _divSqrt_io_inValid_T, {mem_ctrl_fma & _divSqrt_io_inValid_T_2, mem_ctrl_fromint} | {2{mem_ctrl_fma & _divSqrt_io_inValid_T_4}}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :912:{56,72}, :917:{62,78}, :923:{62,78}, :929:{63,100}, :941:19]
    end
    else if (wen[2]) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :947:14]
      wbInfo_1_rd <= wbInfo_2_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
      wbInfo_1_typeTag <= wbInfo_2_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
      wbInfo_1_pipeid <= wbInfo_2_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19]
    end
    wbInfo_1_cp <= ~_GEN_10 & (wen[2] ? wbInfo_2_cp : wbInfo_1_cp);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:20, :941:19, :947:{21,33}, :950:18, :955:{30,52}, :956:22]
    if (_GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, :950:18, :955:{30,52}, :956:22]
      wbInfo_2_rd <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:31, :941:19, :959:37]
      wbInfo_2_typeTag <= mem_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :941:19]
      wbInfo_2_pipeid <= {mem_ctrl_fma & _divSqrt_io_inValid_T, {mem_ctrl_fma & _divSqrt_io_inValid_T_2, mem_ctrl_fromint} | {2{mem_ctrl_fma & _divSqrt_io_inValid_T_4}}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :912:{56,72}, :917:{62,78}, :923:{62,78}, :929:{63,100}, :941:19]
    end
    wbInfo_2_cp <= ~_GEN_11 & wbInfo_2_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:941:19, :950:18, :955:{30,52}, :956:22]
    if (mem_ctrl_toint)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
      wb_toint_exc <= _fpiu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20, :995:31]
    io_sboard_set_REG <= mem_ctrl_fma & _divSqrt_io_inValid_T_4 | mem_ctrl_div | mem_ctrl_sqrt | mem_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27, :917:{62,78}, :1007:{59,95,111,128}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        end	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        ex_reg_valid = _RANDOM[4'h0][1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:29]
        ex_reg_inst = {_RANDOM[4'h0][31:2], _RANDOM[4'h1][1:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:29, :769:30]
        ex_reg_ctrl_ren2 = _RANDOM[4'h1][5];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_ren3 = _RANDOM[4'h1][6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_swap23 = _RANDOM[4'h1][8];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_typeTagIn = _RANDOM[4'h1][10:9];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_typeTagOut = _RANDOM[4'h1][12:11];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_fromint = _RANDOM[4'h1][13];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_toint = _RANDOM[4'h1][14];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_fastpipe = _RANDOM[4'h1][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_fma = _RANDOM[4'h1][16];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_div = _RANDOM[4'h1][17];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_sqrt = _RANDOM[4'h1][18];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_wflags = _RANDOM[4'h1][19];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_reg_ctrl_vec = _RANDOM[4'h1][20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :770:30]
        ex_ra_0 = _RANDOM[4'h1][25:21];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :771:31]
        ex_ra_1 = _RANDOM[4'h1][30:26];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :771:31]
        ex_ra_2 = {_RANDOM[4'h1][31], _RANDOM[4'h2][3:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :769:30, :771:31]
        load_wb = _RANDOM[4'h2][4];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :771:31, :774:24]
        load_wb_typeTag = _RANDOM[4'h2][6:5];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :771:31, :775:34]
        load_wb_data = {_RANDOM[4'h2][31:7], _RANDOM[4'h3], _RANDOM[4'h4][6:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :771:31, :776:31]
        load_wb_tag = _RANDOM[4'h4][11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :776:31, :777:30]
        mem_reg_valid = _RANDOM[4'h4][14];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :776:31, :785:30]
        mem_reg_inst = {_RANDOM[4'h4][31:15], _RANDOM[4'h5][14:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :776:31, :792:31]
        wb_reg_valid = _RANDOM[4'h5][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :793:29]
        mem_ctrl_typeTagOut = _RANDOM[4'h5][26:25];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_fromint = _RANDOM[4'h5][27];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_toint = _RANDOM[4'h5][28];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_fastpipe = _RANDOM[4'h5][29];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_fma = _RANDOM[4'h5][30];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_div = _RANDOM[4'h5][31];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:31, :802:27]
        mem_ctrl_sqrt = _RANDOM[4'h6][0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27]
        mem_ctrl_wflags = _RANDOM[4'h6][1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27]
        mem_ctrl_vec = _RANDOM[4'h6][2];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27]
        wb_ctrl_toint = _RANDOM[4'h6][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27, :803:26]
        divSqrt_waddr = _RANDOM[4'h6][26:22];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27, :899:26]
        wen = _RANDOM[4'h6][30:28];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27, :940:20]
        wbInfo_0_rd = {_RANDOM[4'h6][31], _RANDOM[4'h7][3:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :802:27, :941:19]
        wbInfo_0_typeTag = _RANDOM[4'h7][5:4];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_0_cp = _RANDOM[4'h7][6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_0_pipeid = _RANDOM[4'h7][9:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_1_rd = _RANDOM[4'h7][14:10];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_1_typeTag = _RANDOM[4'h7][16:15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_1_cp = _RANDOM[4'h7][17];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_1_pipeid = _RANDOM[4'h7][20:18];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_2_rd = _RANDOM[4'h7][25:21];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_2_typeTag = _RANDOM[4'h7][27:26];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_2_cp = _RANDOM[4'h7][28];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        wbInfo_2_pipeid = _RANDOM[4'h7][31:29];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :941:19]
        write_port_busy = _RANDOM[4'h8][0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :943:34]
        wb_toint_exc = _RANDOM[4'h8][5:1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :943:34, :995:31]
        io_sboard_set_REG = _RANDOM[4'h8][6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :943:34, :1007:59]
        divSqrt_killed = _RANDOM[4'h8][7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :943:34, :1016:33]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FPUDecoder fp_decoder (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
    .io_inst            (io_inst),
    .io_sigs_wen        (io_dec_wen),
    .io_sigs_ren1       (_fp_decoder_io_sigs_ren1),
    .io_sigs_ren2       (_fp_decoder_io_sigs_ren2),
    .io_sigs_ren3       (_fp_decoder_io_sigs_ren3),
    .io_sigs_swap12     (_fp_decoder_io_sigs_swap12),
    .io_sigs_swap23     (_fp_decoder_io_sigs_swap23),
    .io_sigs_typeTagIn  (_fp_decoder_io_sigs_typeTagIn),
    .io_sigs_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_sigs_fromint    (_fp_decoder_io_sigs_fromint),
    .io_sigs_toint      (_fp_decoder_io_sigs_toint),
    .io_sigs_fastpipe   (_fp_decoder_io_sigs_fastpipe),
    .io_sigs_fma        (_fp_decoder_io_sigs_fma),
    .io_sigs_div        (_fp_decoder_io_sigs_div),
    .io_sigs_sqrt       (_fp_decoder_io_sigs_sqrt),
    .io_sigs_wflags     (_fp_decoder_io_sigs_wflags),
    .io_sigs_vec        (_fp_decoder_io_sigs_vec)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  regfile_32x65 regfile_ext (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
    .R0_addr (ex_ra_2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
    .R0_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R0_clk  (clock),
    .R0_data (_regfile_ext_R0_data),
    .R1_addr (ex_ra_1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
    .R1_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R1_clk  (clock),
    .R1_data (_regfile_ext_R1_data),
    .R2_addr (ex_ra_0),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:771:31]
    .R2_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R2_clk  (clock),
    .R2_data (_regfile_ext_R2_data),
    .W0_addr (waddr),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:964:18]
    .W0_en   (_GEN_4),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:969:35]
    .W0_clk  (clock),
    .W0_data (wdata_1),	// @[generators/rocket-chip/src/main/scala/util/package.scala:39:76]
    .W1_addr (load_wb_tag),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:777:30]
    .W1_en   (load_wb),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:774:24]
    .W1_clk  (clock),
    .W1_data ({_wdata_T_6[63], _wdata_T_8[2:1], _GEN, _GEN_1})	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:344:8, :431:23]
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
  FPUFMAPipe_l3_f32 sfma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:873:20]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_hfma_io_in_valid_T & _write_port_busy_T_20),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:874:{33,48,70}]
    .io_in_bits_ren3   (ex_reg_ctrl_ren3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_swap23 (ex_reg_ctrl_swap23),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm     (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_fmaCmd ({ex_reg_inst[3], ex_reg_inst[2] | ~ex_reg_ctrl_ren3 & ex_reg_inst[27]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :770:30, :858:{30,36,39,53,67}]
    .io_in_bits_in1    ({32'h0, {_regfile_ext_R2_data[31], _regfile_ext_R2_data[52], _regfile_ext_R2_data[30:0]} | ((&(_regfile_ext_R2_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :819:20, :853:13]
    .io_in_bits_in2    ({32'h0, {_regfile_ext_R1_data[31], _regfile_ext_R1_data[52], _regfile_ext_R1_data[30:0]} | ((&(_regfile_ext_R1_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :819:20, :853:13, :854:13]
    .io_in_bits_in3    ({32'h0, {_regfile_ext_R0_data[31], _regfile_ext_R0_data[52], _regfile_ext_R0_data[30:0]} | ((&(_regfile_ext_R0_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :819:20, :853:13, :855:13]
    .io_out_bits_data  (_sfma_io_out_bits_data),
    .io_out_bits_exc   (_sfma_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:873:20]
  FPToInt fpiu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .clock                 (clock),
    .io_in_valid           (ex_reg_valid & (ex_reg_ctrl_toint | ex_reg_ctrl_div | ex_reg_ctrl_sqrt | ex_reg_ctrl_fastpipe & ex_reg_ctrl_wflags)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29, :770:30, :878:{33,51,66,82,103}]
    .io_in_bits_ren2       (ex_reg_ctrl_ren2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_typeTagOut (ex_reg_ctrl_typeTagOut),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_wflags     (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm         (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_typ        (ex_reg_inst[21:20]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :856:27]
    .io_in_bits_fmt        (ex_reg_inst[26:25]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :857:27]
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_bits_in_rm     (_fpiu_io_out_bits_in_rm),
    .io_out_bits_in_in1    (_fpiu_io_out_bits_in_in1),
    .io_out_bits_in_in2    (_fpiu_io_out_bits_in_in2),
    .io_out_bits_lt        (_fpiu_io_out_bits_lt),
    .io_out_bits_store     (io_store_data),
    .io_out_bits_toint     (io_toint_data),
    .io_out_bits_exc       (_fpiu_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  IntToFP ifpu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:887:20]
    .clock                (clock),
    .reset                (reset),
    .io_in_valid          (ex_reg_valid & ex_reg_ctrl_fromint),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29, :770:30, :888:33]
    .io_in_bits_typeTagIn (ex_reg_ctrl_typeTagIn),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_wflags    (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm        (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_typ       (ex_reg_inst[21:20]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :856:27]
    .io_in_bits_in1       (io_fromint_data),
    .io_out_bits_data     (_ifpu_io_out_bits_data),
    .io_out_bits_exc      (_ifpu_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:887:20]
  FPToFP fpmu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:892:20]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (ex_reg_valid & ex_reg_ctrl_fastpipe),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:29, :770:30, :893:33]
    .io_in_bits_ren2       (ex_reg_ctrl_ren2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_typeTagIn  (ex_reg_ctrl_typeTagIn),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_typeTagOut (ex_reg_ctrl_typeTagOut),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_wflags     (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm         (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_bits_data      (_fpmu_io_out_bits_data),
    .io_out_bits_exc       (_fpmu_io_out_bits_exc),
    .io_lt                 (_fpiu_io_out_bits_lt)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:892:20]
  FPUFMAPipe_l4_f64 dfma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:914:28]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_hfma_io_in_valid_T & ex_reg_ctrl_typeTagOut == 2'h2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30, :874:33, :915:{56,78}]
    .io_in_bits_ren3   (ex_reg_ctrl_ren3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_swap23 (ex_reg_ctrl_swap23),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm     (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_fmaCmd ({ex_reg_inst[3], ex_reg_inst[2] | ~ex_reg_ctrl_ren3 & ex_reg_inst[27]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :770:30, :858:{30,36,39,53,67}]
    .io_in_bits_in1    (_regfile_ext_R2_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
    .io_in_bits_in2    (_regfile_ext_R1_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
    .io_in_bits_in3    (_regfile_ext_R0_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:819:20]
    .io_out_bits_data  (_dfma_io_out_bits_data),
    .io_out_bits_exc   (_dfma_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:914:28]
  FPUFMAPipe_l3_f16 hfma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:920:28]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_hfma_io_in_valid_T & _write_port_busy_T_26),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:874:33, :921:{56,78}]
    .io_in_bits_ren3   (ex_reg_ctrl_ren3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_swap23 (ex_reg_ctrl_swap23),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:30]
    .io_in_bits_rm     (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:846:18]
    .io_in_bits_fmaCmd ({ex_reg_inst[3], ex_reg_inst[2] | ~ex_reg_ctrl_ren3 & ex_reg_inst[27]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :770:30, :858:{30,36,39,53,67}]
    .io_in_bits_in1    ({48'h0, {_regfile_ext_R2_data[15], _regfile_ext_R2_data[23], _regfile_ext_R2_data[14:0]} | ((&(_regfile_ext_R2_data[64:60])) & (&{_regfile_ext_R2_data[31], _regfile_ext_R2_data[52], _regfile_ext_R2_data[30:28]}) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :362:32, :372:{26,31}, :819:20, :853:13]
    .io_in_bits_in2    ({48'h0, {_regfile_ext_R1_data[15], _regfile_ext_R1_data[23], _regfile_ext_R1_data[14:0]} | ((&(_regfile_ext_R1_data[64:60])) & (&{_regfile_ext_R1_data[31], _regfile_ext_R1_data[52], _regfile_ext_R1_data[30:28]}) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :362:32, :372:{26,31}, :819:20, :853:13, :854:13]
    .io_in_bits_in3    ({48'h0, {_regfile_ext_R0_data[15], _regfile_ext_R0_data[23], _regfile_ext_R0_data[14:0]} | ((&(_regfile_ext_R0_data[64:60])) & (&{_regfile_ext_R0_data[31], _regfile_ext_R0_data[52], _regfile_ext_R0_data[30:28]}) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :362:32, :372:{26,31}, :819:20, :853:13, :855:13]
    .io_out_bits_data  (_hfma_io_out_bits_data),
    .io_out_bits_exc   (_hfma_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:920:28]
  DivSqrtRecFM_small_e5_s11 divSqrt (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
    .clock             (clock),
    .reset             (divSqrt_killed),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1016:33]
    .io_inReady        (_divSqrt_io_inReady),
    .io_inValid        (divSqrt_inValid & _divSqrt_io_inValid_T),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:923:78, :1015:{41,76}, :1029:45]
    .io_sqrtOp         (mem_ctrl_sqrt),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
    .io_a              ({_fpiu_io_out_bits_in_in1[64], _fpiu_io_out_bits_in_in1[63:61] == 3'h0 | _fpiu_io_out_bits_in_in1[63:61] > 3'h5 ? {_fpiu_io_out_bits_in_in1[63:61], _divSqrt_io_a_expOut_commonCase_T[2:0]} : _divSqrt_io_a_expOut_commonCase_T, _fpiu_io_out_bits_in_in1[51:42]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :877:20]
    .io_b              ({_fpiu_io_out_bits_in_in2[64], _fpiu_io_out_bits_in_in2[63:61] == 3'h0 | _fpiu_io_out_bits_in_in2[63:61] > 3'h5 ? {_fpiu_io_out_bits_in_in2[63:61], _divSqrt_io_b_expOut_commonCase_T[2:0]} : _divSqrt_io_b_expOut_commonCase_T, _fpiu_io_out_bits_in_in2[51:42]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :877:20]
    .io_roundingMode   (_fpiu_io_out_bits_in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .io_outValid_div   (_divSqrt_io_outValid_div),
    .io_outValid_sqrt  (_divSqrt_io_outValid_sqrt),
    .io_out            (_divSqrt_io_out),
    .io_exceptionFlags (_divSqrt_io_exceptionFlags)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  DivSqrtRecFM_small_e8_s24 divSqrt_1 (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
    .clock             (clock),
    .reset             (divSqrt_killed),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1016:33]
    .io_inReady        (_divSqrt_1_io_inReady),
    .io_inValid        (divSqrt_inValid & _divSqrt_io_inValid_T_2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:912:72, :1015:{41,76}, :1029:45]
    .io_sqrtOp         (mem_ctrl_sqrt),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
    .io_a              ({_fpiu_io_out_bits_in_in1[64], _fpiu_io_out_bits_in_in1[63:61] == 3'h0 | _fpiu_io_out_bits_in_in1[63:61] > 3'h5 ? {_fpiu_io_out_bits_in_in1[63:61], _divSqrt_io_a_expOut_commonCase_T_3[5:0]} : _divSqrt_io_a_expOut_commonCase_T_3, _fpiu_io_out_bits_in_in1[51:29]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :877:20]
    .io_b              ({_fpiu_io_out_bits_in_in2[64], _fpiu_io_out_bits_in_in2[63:61] == 3'h0 | _fpiu_io_out_bits_in_in2[63:61] > 3'h5 ? {_fpiu_io_out_bits_in_in2[63:61], _divSqrt_io_b_expOut_commonCase_T_3[5:0]} : _divSqrt_io_b_expOut_commonCase_T_3, _fpiu_io_out_bits_in_in2[51:29]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :877:20]
    .io_roundingMode   (_fpiu_io_out_bits_in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .io_outValid_div   (_divSqrt_1_io_outValid_div),
    .io_outValid_sqrt  (_divSqrt_1_io_outValid_sqrt),
    .io_out            (_divSqrt_1_io_out),
    .io_exceptionFlags (_divSqrt_1_io_exceptionFlags)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  DivSqrtRecFM_small_e11_s53 divSqrt_2 (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
    .clock             (clock),
    .reset             (divSqrt_killed),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1016:33]
    .io_inReady        (_divSqrt_2_io_inReady),
    .io_inValid        (divSqrt_inValid & _divSqrt_io_inValid_T_4),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:917:78, :1015:{41,76}, :1029:45]
    .io_sqrtOp         (mem_ctrl_sqrt),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:27]
    .io_a              (_fpiu_io_out_bits_in_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .io_b              (_fpiu_io_out_bits_in_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .io_roundingMode   (_fpiu_io_out_bits_in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:877:20]
    .io_outValid_div   (_divSqrt_2_io_outValid_div),
    .io_outValid_sqrt  (_divSqrt_2_io_outValid_sqrt),
    .io_out            (_divSqrt_2_io_out),
    .io_exceptionFlags (_divSqrt_2_io_exceptionFlags)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1028:55]
  assign io_fcsr_flags_valid = wb_toint_valid | divSqrt_wen | wen[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:20, :969:30, :994:37, :996:{41,56}, :1038:66, :1039:21]
  assign io_fcsr_flags_bits = (wb_toint_valid ? wb_toint_exc : 5'h0) | (divSqrt_wen ? divSqrt_flags : 5'h0) | (wen[0] ? (_GEN_3 ? _hfma_io_out_bits_exc : _io_sboard_clr_T_3 ? _dfma_io_out_bits_exc : _wexc_T_2 ? _sfma_io_out_bits_exc : _wexc_T ? _ifpu_io_out_bits_exc : _fpmu_io_out_bits_exc) : 5'h0);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :873:20, :887:20, :892:20, :914:28, :920:28, :940:20, :969:30, :994:37, :995:31, :998:{8,44}, :999:{8,42}, :1000:8, :1038:66, :1039:21, :1041:23, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  assign io_fcsr_rdy = ~((|{ex_reg_valid & ex_reg_ctrl_wflags | mem_reg_valid & mem_ctrl_wflags | wb_toint_valid, wen}) | divSqrt_inFlight);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:29, :770:30, :785:30, :802:27, :940:20, :994:37, :1002:72, :1003:{18,33,51,68,87,120,131}, :1036:34, :1046:{27,46}]
  assign io_nack_mem = io_nack_mem_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1004:{35,62}]
  assign io_illegal_rm = io_inst[14:12] == 3'h5 | io_inst[14:12] == 3'h6 | (&(io_inst[14:12])) & io_fcsr_rm > 3'h4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1012:{27,53,71,79,93}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  assign io_dec_ren1 = _fp_decoder_io_sigs_ren1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_dec_ren2 = _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_dec_ren3 = _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_sboard_set = wb_reg_valid & io_sboard_set_REG;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :793:29, :1007:{49,59}]
  assign io_sboard_clr = divSqrt_wen | wen[0] & _io_sboard_clr_T_3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:20, :969:30, :1008:{49,60}, :1038:66, :1039:21, generators/rocket-chip/src/main/scala/util/package.scala:39:86]
  assign io_sboard_clra = waddr;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :964:18]
endmodule

