// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FPUFMAPipe_l3_f16(	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
  input         io_in_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input         io_in_bits_ren3,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input         io_in_bits_swap23,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input  [2:0]  io_in_bits_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input  [1:0]  io_in_bits_fmaCmd,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input  [64:0] io_in_bits_in1,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input  [64:0] io_in_bits_in2,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  input  [64:0] io_in_bits_in3,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  output [64:0] io_out_bits_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
  output [4:0]  io_out_bits_exc	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
);

  wire [16:0] _fma_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:719:19]
  reg         valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:707:22]
  reg  [2:0]  in_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
  reg  [1:0]  in_fmaCmd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
  reg  [64:0] in_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
  reg  [64:0] in_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
  reg  [64:0] in_in3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
    valid <= io_in_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:707:22]
    if (io_in_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14]
      in_rm <= io_in_bits_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
      in_fmaCmd <= io_in_bits_fmaCmd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
      in_in1 <= io_in_bits_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
      in_in2 <= io_in_bits_swap23 ? 65'h8000 : io_in_bits_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15, :714:8, :715:{23,32}]
      in_in3 <= io_in_bits_ren3 | io_in_bits_swap23 ? io_in_bits_in3 : {48'h0, (io_in_bits_in1[16:0] ^ io_in_bits_in2[16:0]) & 17'h10000};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:702:14, :708:15, :711:{32,50}, :714:8, :716:{21,37,46}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
        end	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
        valid = _RANDOM[3'h0][0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :707:22]
        in_rm = _RANDOM[3'h0][22:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :707:22, :708:15]
        in_fmaCmd = _RANDOM[3'h0][24:23];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :707:22, :708:15]
        in_in1 = {_RANDOM[3'h0][31:29], _RANDOM[3'h1], _RANDOM[3'h2][29:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :707:22, :708:15]
        in_in2 = {_RANDOM[3'h2][31:30], _RANDOM[3'h3], _RANDOM[3'h4][30:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :708:15]
        in_in3 = {_RANDOM[3'h4][31], _RANDOM[3'h5], _RANDOM[3'h6]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :708:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MulAddRecFNPipe_l2_e5_s11 fma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:719:19]
    .clock             (clock),
    .reset             (reset),
    .io_validin        (valid),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:707:22]
    .io_op             (in_fmaCmd),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
    .io_a              (in_in1[16:0]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15, :724:12]
    .io_b              (in_in2[16:0]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15, :725:12]
    .io_c              (in_in3[16:0]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15, :726:12]
    .io_roundingMode   (in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:708:15]
    .io_out            (_fma_io_out),
    .io_exceptionFlags (io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:719:19]
  assign io_out_bits_data = {48'h0, _fma_io_out};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:697:7, :711:50, :719:19, :729:12]
endmodule

