// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SBToTL(	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
  input          clock,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
  input          reset,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
  input          auto_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output         auto_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]   auto_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]   auto_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0]  auto_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]   auto_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output         auto_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input          auto_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]   auto_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]   auto_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]   auto_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]   auto_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input          auto_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]   auto_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input          auto_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input          io_rdEn,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  input          io_wrEn,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  input  [127:0] io_addrIn,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  input  [127:0] io_dataIn,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  input  [2:0]   io_sizeIn,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLegal,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_wrLegal,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdDone,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_wrDone,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_respError,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output [7:0]   io_dataOut,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_0,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_1,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_2,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_3,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_4,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_5,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_6,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output         io_rdLoad_7,	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
  output [2:0]   io_sbStateOut	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16]
);

  wire            _d_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire            _d_q_io_deq_bits_denied;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire            _d_q_io_deq_bits_corrupt;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg  [2:0]      sbState;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
  wire            _rdTxValid_T = sbState == 3'h3;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :299:25]
  wire            _io_wrDone_T = sbState == 3'h4;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :299:62]
  wire            d_q_io_deq_ready = _rdTxValid_T | _io_wrDone_T;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:299:{25,50,62}]
  reg  [3:0]      counter;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:307:26]
  wire [7:0][7:0] _GEN = {{io_dataIn[63:56]}, {io_dataIn[55:48]}, {io_dataIn[47:40]}, {io_dataIn[39:32]}, {io_dataIn[31:24]}, {io_dataIn[23:16]}, {io_dataIn[15:8]}, {io_dataIn[7:0]}};	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:309:63, :310:15]
  wire [115:0]    _GEN_0 = {io_addrIn[127:14], ~(io_addrIn[13:12])};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [114:0]    _GEN_1 = {io_addrIn[127:21], io_addrIn[20:17] ^ 4'h8, io_addrIn[15:12]};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [111:0]    _GEN_2 = {io_addrIn[127:26], io_addrIn[25:16] ^ 10'h200};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [115:0]    _GEN_3 = {io_addrIn[127:26], io_addrIn[25:12] ^ 14'h2010};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [111:0]    _GEN_4 = {io_addrIn[127:28], io_addrIn[27:16] ^ 12'h800};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [101:0]    _GEN_5 = {io_addrIn[127:28], ~(io_addrIn[27:26])};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [113:0]    _GEN_6 = {io_addrIn[127:31], io_addrIn[30:14] ^ 17'h19000};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire [96:0]     _GEN_7 = {io_addrIn[127:32], ~(io_addrIn[31])};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
  wire            io_rdLegal_0 = ~(|(io_addrIn[127:13])) | ~(|_GEN_0) | {io_addrIn[127:17], ~(io_addrIn[16])} == 112'h0 | ~(|_GEN_1) | ~(|_GEN_2) | ~(|_GEN_3) | ~(|_GEN_4) | ~(|_GEN_5) | ~(|_GEN_6) | ~(|_GEN_7);	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
  wire            io_wrLegal_0 = ~(|(io_addrIn[127:13])) | ~(|_GEN_0) | ~(|_GEN_1) | ~(|_GEN_2) | ~(|_GEN_3) | ~(|_GEN_4) | ~(|_GEN_5) | ~(|_GEN_6) | ~(|_GEN_7);	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:274:16, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
  wire            _nodeOut_a_valid_T = sbState == 3'h1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :322:18]
  wire            _nodeOut_a_valid_T_1 = sbState == 3'h2;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :338:29]
  wire            rdTxValid = _rdTxValid_T & _d_q_io_deq_valid & d_q_io_deq_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:299:{25,50}, :339:{53,70}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire            txLast = {4'h0, counter} == (8'h1 << io_sizeIn) - 8'h1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:307:26, :340:{29,39,53}]
  wire            _GEN_8 = sbState == 3'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :349:19]
  wire            nodeOut_a_valid = _nodeOut_a_valid_T | _nodeOut_a_valid_T_1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:322:18, :338:29, :366:52]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
      if (~reset & ~(_GEN_8 | _nodeOut_a_valid_T | _nodeOut_a_valid_T_1 | _rdTxValid_T | _io_wrDone_T)) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:299:{25,62}, :322:18, :338:29, :349:19, :373:{12,35}, :374:44, :375:45, :376:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
          $error("Assertion failed: SBA state machine in undefined state\n    at SBA.scala:373 assert (sbState === Idle.id.U ||\n");	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:373:12]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire            wrTxValid = _nodeOut_a_valid_T_1 & nodeOut_a_valid & auto_out_a_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:338:{29,53,69}, :366:52]
  wire            _counter_T_2 = wrTxValid | rdTxValid;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:338:{53,69}, :339:{53,70}, :341:31]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      sbState <= 3'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
      counter <= 4'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:307:26]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      if (_GEN_8) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:349:19]
        if (io_rdEn & io_rdLegal_0)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:350:30, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
          sbState <= 3'h1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
        else if (io_wrEn & io_wrLegal_0)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:351:30, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
          sbState <= 3'h2;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
      end
      else if (_nodeOut_a_valid_T) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:322:18]
        if (nodeOut_a_valid & auto_out_a_ready)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:353:35, :366:52]
          sbState <= 3'h3;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
      end
      else if (_nodeOut_a_valid_T_1) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:338:29]
        if (wrTxValid & txLast)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:338:{53,69}, :340:29, :355:32]
          sbState <= 3'h4;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
      end
      else if (_rdTxValid_T ? rdTxValid & txLast : _io_wrDone_T & _d_q_io_deq_valid & d_q_io_deq_ready)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26, :299:{25,50,62}, :339:{53,70}, :340:29, :356:49, :357:{15,21,32}, :358:50, :359:{15,21,36}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
        sbState <= 3'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:295:26]
      if (_counter_T_2 & txLast)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:340:29, :341:{31,45}]
        counter <= 4'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:307:26]
      else if (_counter_T_2)	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:341:31]
        counter <= counter + 4'h1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:307:26, :342:63]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
        sbState = _RANDOM[/*Zero width*/ 1'b0][2:0];	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :295:26]
        counter = _RANDOM[/*Zero width*/ 1'b0][6:3];	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :295:26, :307:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue2_TLBundleD_a32d8s1k3z4u d_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (auto_out_d_ready),
    .io_enq_valid        (auto_out_d_valid),
    .io_enq_bits_opcode  (auto_out_d_bits_opcode),
    .io_enq_bits_param   (auto_out_d_bits_param),
    .io_enq_bits_size    (auto_out_d_bits_size),
    .io_enq_bits_sink    (auto_out_d_bits_sink),
    .io_enq_bits_denied  (auto_out_d_bits_denied),
    .io_enq_bits_data    (auto_out_d_bits_data),
    .io_enq_bits_corrupt (auto_out_d_bits_corrupt),
    .io_deq_ready        (d_q_io_deq_ready),	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:299:50]
    .io_deq_valid        (_d_q_io_deq_valid),
    .io_deq_bits_denied  (_d_q_io_deq_bits_denied),
    .io_deq_bits_data    (io_dataOut),
    .io_deq_bits_corrupt (_d_q_io_deq_bits_corrupt)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_a_valid = nodeOut_a_valid;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :366:52]
  assign auto_out_a_bits_opcode = {_nodeOut_a_valid_T, 2'h0};	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :322:{18,42,54}, :323:54]
  assign auto_out_a_bits_size = {1'h0, io_sizeIn};	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:463:15]
  assign auto_out_a_bits_address = io_addrIn[31:0];	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31]
  assign auto_out_a_bits_data = _nodeOut_a_valid_T ? 8'h0 : _GEN[counter[2:0]];	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :310:{15,33}, :322:{18,42,54}, :323:54]
  assign io_rdLegal = io_rdLegal_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
  assign io_wrLegal = io_wrLegal_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
  assign io_rdDone = rdTxValid & txLast;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :339:{53,70}, :340:29, :362:29]
  assign io_wrDone = _io_wrDone_T & _d_q_io_deq_valid & d_q_io_deq_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :299:{50,62}, :363:{54,71}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_respError = _d_q_io_deq_bits_denied | _d_q_io_deq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :335:35, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_rdLoad_0 = rdTxValid & counter == 4'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_1 = rdTxValid & counter == 4'h1;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_2 = rdTxValid & counter == 4'h2;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_3 = rdTxValid & counter == 4'h3;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_4 = rdTxValid & counter == 4'h4;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_5 = rdTxValid & counter == 4'h5;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_6 = rdTxValid & counter == 4'h6;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_rdLoad_7 = rdTxValid & counter == 4'h7;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :307:26, :339:{53,70}, :345:{33,45}]
  assign io_sbStateOut = sbState;	// @[generators/rocket-chip/src/main/scala/devices/debug/SBA.scala:273:9, :295:26]
endmodule

