// Generated by CIRCT firtool-1.75.0
module SinkX(	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:28:7]
  input         clock,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:28:7]
  input         reset,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:28:7]
  input         io_req_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  output        io_req_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  output [15:0] io_req_bits_tag,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  output [9:0]  io_req_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  output        io_x_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  input         io_x_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
  input  [31:0] io_x_bits_address	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:30:14]
);

  wire [31:0] _x_q_io_deq_bits_address;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue1_SinkXRequest x_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (io_x_ready),
    .io_enq_valid        (io_x_valid),
    .io_enq_bits_address (io_x_bits_address),
    .io_deq_ready        (io_req_ready),
    .io_deq_valid        (io_req_valid),
    .io_deq_bits_address (_x_q_io_deq_bits_address)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_req_bits_tag = _x_q_io_deq_bits_address[31:16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Parameters.scala:215:22, :216:19, generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:28:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_req_bits_set = _x_q_io_deq_bits_address[15:6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Parameters.scala:215:22, :217:28, generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SinkX.scala:28:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

