// Generated by CIRCT firtool-1.75.0
module SourceX(	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:29:7]
  input  clock,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:29:7]
  input  reset,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:29:7]
  output io_req_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:31:14]
  input  io_req_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:31:14]
  output io_x_valid	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceX.scala:31:14]
);

  Queue1_SourceXRequest io_x_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (io_req_ready),
    .io_enq_valid (io_req_valid),
    .io_deq_valid (io_x_valid)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

