// Generated by CIRCT firtool-1.75.0
module SynchronizerShiftReg_w1_d3(	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:169:7]
  input  clock,	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:169:7]
  input  io_d,	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:36:14]
  output io_q	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:36:14]
);

  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d),
    .io_q  (io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
endmodule

