// Generated by CIRCT firtool-1.75.0
module TLBusBypass(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:41:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:41:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:41:9]
  input         auto_node_out_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_out_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_node_out_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [8:0]  auto_node_out_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_node_out_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_out_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_node_out_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_node_out_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_node_out_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_node_out_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_node_out_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_in_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_node_in_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_node_in_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [8:0]  auto_node_in_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_node_in_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_node_in_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_in_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_in_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_node_in_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_node_in_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         io_bypass	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:42:16]
);

  wire       _error_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
  wire       _error_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
  wire [2:0] _error_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
  wire       _error_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
  wire       _error_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
  wire       _bar_auto_out_0_a_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
  wire [2:0] _bar_auto_out_0_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
  wire       _bar_auto_out_0_d_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
  TLBusBypassBar bar (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
    .clock                     (clock),
    .reset                     (reset),
    .auto_in_a_ready           (auto_node_in_in_a_ready),
    .auto_in_a_valid           (auto_node_in_in_a_valid),
    .auto_in_a_bits_opcode     (auto_node_in_in_a_bits_opcode),
    .auto_in_a_bits_address    (auto_node_in_in_a_bits_address),
    .auto_in_a_bits_data       (auto_node_in_in_a_bits_data),
    .auto_in_d_ready           (auto_node_in_in_d_ready),
    .auto_in_d_valid           (auto_node_in_in_d_valid),
    .auto_in_d_bits_denied     (auto_node_in_in_d_bits_denied),
    .auto_in_d_bits_data       (auto_node_in_in_d_bits_data),
    .auto_in_d_bits_corrupt    (auto_node_in_in_d_bits_corrupt),
    .auto_out_1_a_ready        (auto_node_out_out_a_ready),
    .auto_out_1_a_valid        (auto_node_out_out_a_valid),
    .auto_out_1_a_bits_opcode  (auto_node_out_out_a_bits_opcode),
    .auto_out_1_a_bits_address (auto_node_out_out_a_bits_address),
    .auto_out_1_a_bits_data    (auto_node_out_out_a_bits_data),
    .auto_out_1_d_ready        (auto_node_out_out_d_ready),
    .auto_out_1_d_valid        (auto_node_out_out_d_valid),
    .auto_out_1_d_bits_opcode  (auto_node_out_out_d_bits_opcode),
    .auto_out_1_d_bits_denied  (auto_node_out_out_d_bits_denied),
    .auto_out_1_d_bits_data    (auto_node_out_out_d_bits_data),
    .auto_out_1_d_bits_corrupt (auto_node_out_out_d_bits_corrupt),
    .auto_out_0_a_ready        (_error_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .auto_out_0_a_valid        (_bar_auto_out_0_a_valid),
    .auto_out_0_a_bits_opcode  (_bar_auto_out_0_a_bits_opcode),
    .auto_out_0_d_ready        (_bar_auto_out_0_d_ready),
    .auto_out_0_d_valid        (_error_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .auto_out_0_d_bits_opcode  (_error_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .auto_out_0_d_bits_denied  (_error_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .auto_out_0_d_bits_corrupt (_error_auto_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .io_bypass                 (io_bypass)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
  TLError_1 error (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
    .clock                  (clock),
    .reset                  (reset),
    .auto_in_a_ready        (_error_auto_in_a_ready),
    .auto_in_a_valid        (_bar_auto_out_0_a_valid),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
    .auto_in_a_bits_opcode  (_bar_auto_out_0_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
    .auto_in_d_ready        (_bar_auto_out_0_d_ready),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:17:33]
    .auto_in_d_valid        (_error_auto_in_d_valid),
    .auto_in_d_bits_opcode  (_error_auto_in_d_bits_opcode),
    .auto_in_d_bits_denied  (_error_auto_in_d_bits_denied),
    .auto_in_d_bits_corrupt (_error_auto_in_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:27:40]
endmodule

