// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLDebugModuleOuter(	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
  output        auto_dmi_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_dmi_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_dmi_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [6:0]  auto_dmi_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_dmi_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_dmi_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_dmi_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_dmi_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        io_ctrl_dmactive,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  input         io_ctrl_dmactiveAck,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  input         io_innerCtrl_ready,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  output        io_innerCtrl_valid,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  output        io_innerCtrl_bits_resumereq,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  output [9:0]  io_innerCtrl_bits_hartsel,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  output        io_innerCtrl_bits_ackhavereset,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  output        io_innerCtrl_bits_hrmask_0,	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
  input         io_hgDebugInt_0	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:348:16]
);

  wire       out_woready_9;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire       DMCONTROLWrData_setresethaltreq;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire       DMCONTROLWrData_clrresethaltreq;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  reg        DMCONTROLReg_haltreq;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
  reg  [9:0] DMCONTROLReg_hartsello;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
  reg        DMCONTROLReg_ndmreset;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
  reg        DMCONTROLReg_dmactive;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
  reg        hrmaskReg_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:519:28]
  wire       _GEN = DMCONTROLReg_hartsello == 10'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, :446:35]
  wire       hrmaskNxt_0 = ~(~DMCONTROLReg_dmactive | out_woready_9 & DMCONTROLWrData_clrresethaltreq & _GEN) & (out_woready_9 & DMCONTROLWrData_setresethaltreq & _GEN | hrmaskReg_0);	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, :398:11, :446:35, :519:28, :521:15, :523:44, :524:30, :525:{39,74,102}, :526:30, :527:{39,74,102}, :528:30, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire       _out_T_3 = {auto_dmi_in_a_bits_address[4], auto_dmi_in_a_bits_address[2]} == 2'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  assign DMCONTROLWrData_clrresethaltreq = auto_dmi_in_a_bits_data[2];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign DMCONTROLWrData_setresethaltreq = auto_dmi_in_a_bits_data[3];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_9 = auto_dmi_in_a_valid & auto_dmi_in_d_ready & auto_dmi_in_a_bits_opcode != 3'h4 & ~(auto_dmi_in_a_bits_address[3]) & _out_T_3;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  reg        debugIntRegs_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:600:31]
  reg        innerCtrlValidReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:630:36]
  reg        innerCtrlResumeReqReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:631:40]
  reg        innerCtrlAckHaveResetReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:632:43]
  wire       io_innerCtrl_valid_0 = out_woready_9 | innerCtrlValidReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:630:36, :641:54, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire       io_innerCtrl_bits_resumereq_0 = out_woready_9 & auto_dmi_in_a_bits_data[30] | innerCtrlResumeReqReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:631:40, :643:{54,83}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire       io_innerCtrl_bits_ackhavereset_0 = out_woready_9 & auto_dmi_in_a_bits_data[28] | innerCtrlAckHaveResetReg;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:632:43, :644:{57,89}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  always @(posedge clock or posedge reset) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      DMCONTROLReg_haltreq <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      DMCONTROLReg_hartsello <= 10'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      DMCONTROLReg_ndmreset <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      DMCONTROLReg_dmactive <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      hrmaskReg_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:519:28]
      debugIntRegs_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:600:31]
      innerCtrlValidReg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:630:36]
      innerCtrlResumeReqReg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:631:40]
      innerCtrlAckHaveResetReg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:632:43]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      DMCONTROLReg_haltreq <= DMCONTROLReg_dmactive & (out_woready_9 ? auto_dmi_in_a_bits_data[31] : DMCONTROLReg_haltreq);	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, :397:18, :398:22, :399:20, :405:{47,75}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (DMCONTROLReg_dmactive) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      end
      else	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
        DMCONTROLReg_hartsello <= 10'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
      DMCONTROLReg_ndmreset <= DMCONTROLReg_dmactive & (out_woready_9 ? auto_dmi_in_a_bits_data[1] : DMCONTROLReg_ndmreset);	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, :397:18, :398:22, :399:20, :401:{47,75}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_9)	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        DMCONTROLReg_dmactive <= auto_dmi_in_a_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      hrmaskReg_0 <= hrmaskNxt_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:519:28, :523:44, :524:30, :525:102, :526:30, :527:102]
      debugIntRegs_0 <= DMCONTROLReg_dmactive & (out_woready_9 ? auto_dmi_in_a_bits_data[31] : debugIntRegs_0);	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31, :600:31, :602:17, :610:44, :611:32, :614:96, :615:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      innerCtrlValidReg <= io_innerCtrl_valid_0 & ~io_innerCtrl_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:630:36, :637:{52,54}, :641:54]
      innerCtrlResumeReqReg <= io_innerCtrl_bits_resumereq_0 & ~io_innerCtrl_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:631:40, :637:54, :638:61, :643:83]
      innerCtrlAckHaveResetReg <= io_innerCtrl_bits_ackhavereset_0 & ~io_innerCtrl_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:632:43, :637:54, :639:64, :644:89]
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
        end	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
        DMCONTROLReg_haltreq = _RANDOM[2'h0][0];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
        DMCONTROLReg_hartsello = _RANDOM[2'h0][15:6];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
        DMCONTROLReg_ndmreset = _RANDOM[2'h0][30];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
        DMCONTROLReg_dmactive = _RANDOM[2'h0][31];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
        hrmaskReg_0 = _RANDOM[2'h2][0];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :519:28]
        debugIntRegs_0 = _RANDOM[2'h2][1];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :519:28, :600:31]
        innerCtrlValidReg = _RANDOM[2'h2][2];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :519:28, :630:36]
        innerCtrlResumeReqReg = _RANDOM[2'h2][3];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :519:28, :631:40]
        innerCtrlAckHaveResetReg = _RANDOM[2'h2][4];	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :519:28, :632:43]
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
        DMCONTROLReg_haltreq = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
        DMCONTROLReg_hartsello = 10'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
        DMCONTROLReg_ndmreset = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
        DMCONTROLReg_dmactive = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:379:31]
        hrmaskReg_0 = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:519:28]
        debugIntRegs_0 = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:600:31]
        innerCtrlValidReg = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:630:36]
        innerCtrlResumeReqReg = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:631:40]
        innerCtrlAckHaveResetReg = 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:632:43]
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign auto_dmi_in_a_ready = auto_dmi_in_d_ready;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
  assign auto_dmi_in_d_valid = auto_dmi_in_a_valid;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9]
  assign auto_dmi_in_d_bits_data = _out_T_3 ? (auto_dmi_in_a_bits_address[3] ? 32'h118380 : {DMCONTROLReg_haltreq, 29'h0, DMCONTROLReg_ndmreset, DMCONTROLReg_dmactive & io_ctrl_dmactiveAck}) : 32'h0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31, :534:43, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
  assign auto_int_out_0 = debugIntRegs_0 | io_hgDebugInt_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :600:31, :605:60]
  assign io_ctrl_dmactive = DMCONTROLReg_dmactive;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
  assign io_innerCtrl_valid = io_innerCtrl_valid_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :641:54]
  assign io_innerCtrl_bits_resumereq = io_innerCtrl_bits_resumereq_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :643:83]
  assign io_innerCtrl_bits_hartsel = DMCONTROLReg_hartsello;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :379:31]
  assign io_innerCtrl_bits_ackhavereset = io_innerCtrl_bits_ackhavereset_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :644:89]
  assign io_innerCtrl_bits_hrmask_0 = hrmaskNxt_0;	// @[generators/rocket-chip/src/main/scala/devices/debug/Debug.scala:340:9, :523:44, :524:30, :525:102, :526:30, :527:102]
endmodule

