// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLGPIO(	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  input         clock,	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  input         reset,	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  output        auto_int_xing_out_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_control_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_control_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_control_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_control_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_control_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [30:0] auto_control_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_control_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_control_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_control_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_control_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_control_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_control_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_control_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_control_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_io_out_pins_0_i_ival,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_oval,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_oe,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_ie,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_pue,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_ds,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_ds1,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_io_out_pins_0_o_poe	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire              out_woready_12;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_6;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              _out_wofireMux_T_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_backSel_0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire              _ieReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22]
  wire              _pueReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22]
  wire              _oeReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22]
  reg               portReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24]
  reg               dsReg_0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23]
  reg               valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27]
  reg               highIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26]
  reg               lowIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:91:26]
  reg               riseIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:92:26]
  reg               fallIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:93:26]
  reg               highIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26]
  reg               lowIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:95:26]
  reg               riseIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:96:26]
  reg               fallIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:97:26]
  reg               passthruHighIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34]
  reg               passthruLowIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:99:34]
  reg               xorReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:106:26]
  wire              in_bits_read = auto_control_xing_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
  wire              _out_T_21 = auto_control_xing_in_a_bits_address[11:7] == 5'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  assign out_backSel_0 = auto_control_xing_in_a_bits_address[6:3] == 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign _out_wofireMux_T_2 = auto_control_xing_in_a_valid & auto_control_xing_in_d_ready & ~in_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  assign out_woready_6 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h1 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_12 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h2 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_16 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h3 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_20 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h4 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_3 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h5 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_8 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h6 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_woready_18 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h8 & _out_T_21;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [15:0]       _GEN = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}, {_out_T_21}};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire [15:0][32:0] _GEN_0 = {{33'h0}, {33'h0}, {33'h0}, {33'h0}, {33'h0}, {33'h0}, {{32'h0, passthruLowIeReg}}, {{passthruHighIeReg, 31'h0, xorReg}}, {33'h0}, {{lowIpReg, 31'h0, lowIeReg}}, {{highIpReg, 31'h0, highIeReg}}, {{fallIpReg, 31'h0, fallIeReg}}, {{riseIpReg, 31'h0, riseIeReg}}, {{dsReg_0, 31'h0, _pueReg_io_q}}, {{portReg, 31'h0, _oeReg_io_q}}, {{_ieReg_io_q, 31'h0, valueReg}}};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :76:22, :77:22, :78:23, :79:22, :87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :106:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  always @(posedge clock) begin	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    if (reset) begin	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      portReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24]
      dsReg_0 <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :78:23]
      valueReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :87:27]
      highIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :90:26]
      lowIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :91:26]
      riseIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :92:26]
      fallIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :93:26]
      highIpReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :94:26]
      lowIpReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :95:26]
      riseIpReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :96:26]
      fallIpReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :97:26]
      passthruHighIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :98:34]
      passthruLowIeReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :99:34]
      xorReg <= 1'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :106:26]
    end
    else begin	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      if (out_woready_6 & auto_control_xing_in_a_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        portReg <= auto_control_xing_in_a_bits_data[32];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_12 & auto_control_xing_in_a_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        dsReg_0 <= auto_control_xing_in_a_bits_data[32];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      valueReg <= _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      if (out_woready_3 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        highIeReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_8 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        lowIeReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:91:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_16 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        riseIeReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:92:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        fallIeReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:93:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      highIpReg <= ~(~highIpReg | out_woready_3 & auto_control_xing_in_a_bits_mask[4] & auto_control_xing_in_a_bits_data[32]) | valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :94:26, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      lowIpReg <= ~(~lowIpReg | out_woready_8 & auto_control_xing_in_a_bits_mask[4] & auto_control_xing_in_a_bits_data[32]) | ~valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :95:26, :112:14, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      riseIpReg <= ~(~riseIpReg | out_woready_16 & auto_control_xing_in_a_bits_mask[4] & auto_control_xing_in_a_bits_data[32]) | ~valueReg & _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :96:26, :112:{14,24}, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      fallIpReg <= ~(~fallIpReg | out_woready_20 & auto_control_xing_in_a_bits_mask[4] & auto_control_xing_in_a_bits_data[32]) | valueReg & ~_inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :97:26, :113:{23,25}, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      if (out_woready_18 & auto_control_xing_in_a_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        passthruHighIeReg <= auto_control_xing_in_a_bits_data[32];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h9 & _out_T_21 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        passthruLowIeReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:99:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_18 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        xorReg <= auto_control_xing_in_a_bits_data[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:106:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    initial begin	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
        portReg = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24]
        dsReg_0 = _RANDOM[/*Zero width*/ 1'b0][1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :78:23]
        valueReg = _RANDOM[/*Zero width*/ 1'b0][3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :87:27]
        highIeReg = _RANDOM[/*Zero width*/ 1'b0][4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :90:26]
        lowIeReg = _RANDOM[/*Zero width*/ 1'b0][5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :91:26]
        riseIeReg = _RANDOM[/*Zero width*/ 1'b0][6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :92:26]
        fallIeReg = _RANDOM[/*Zero width*/ 1'b0][7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :93:26]
        highIpReg = _RANDOM[/*Zero width*/ 1'b0][8];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :94:26]
        lowIpReg = _RANDOM[/*Zero width*/ 1'b0][9];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :95:26]
        riseIpReg = _RANDOM[/*Zero width*/ 1'b0][10];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :96:26]
        fallIpReg = _RANDOM[/*Zero width*/ 1'b0][11];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :97:26]
        passthruHighIeReg = _RANDOM[/*Zero width*/ 1'b0][12];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :98:34]
        passthruLowIeReg = _RANDOM[/*Zero width*/ 1'b0][13];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :99:34]
        xorReg = _RANDOM[/*Zero width*/ 1'b0][15];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :106:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  IntSyncCrossingSource_n1x1 intsource (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (clock),
    .reset           (reset),
    .auto_in_0       (riseIpReg & riseIeReg | fallIpReg & fallIeReg | highIpReg & highIeReg | lowIpReg & lowIeReg | valueReg & passthruHighIeReg | ~valueReg & passthruLowIeReg),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{40,58}, :235:{42,60}, :236:{42,60}, :237:{41,58}, :238:{41,67}, :239:{27,42}]
    .auto_out_sync_0 (auto_int_xing_out_sync_0)
  );	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
  AsyncResetRegVec_w1_i0 oeReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_q  (_oeReg_io_q),
    .io_en (out_woready_6 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22]
  AsyncResetRegVec_w1_i0 pueReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_q  (_pueReg_io_q),
    .io_en (out_woready_12 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22]
  AsyncResetRegVec_w1_i0 ieReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[32]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_q  (_ieReg_io_q),
    .io_en (_out_wofireMux_T_2 & out_backSel_0 & _out_T_21 & auto_control_xing_in_a_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22]
  AsyncResetRegVec_w1_i0 poeReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:81:22]
    .clock (clock),
    .reset (reset),
    .io_d  (1'h0),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
    .io_q  (auto_io_out_pins_0_o_poe),
    .io_en (1'h0)	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:81:22]
  SynchronizerShiftReg_w1_d3 inSyncReg_inSyncReg (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (auto_io_out_pins_0_i_ival),
    .io_q  (_inSyncReg_inSyncReg_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  assign auto_control_xing_in_a_ready = auto_control_xing_in_d_ready;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  assign auto_control_xing_in_d_valid = auto_control_xing_in_a_valid;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  assign auto_control_xing_in_d_bits_opcode = {2'h0, in_bits_read};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :105:19]
  assign auto_control_xing_in_d_bits_size = auto_control_xing_in_a_bits_size;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  assign auto_control_xing_in_d_bits_source = auto_control_xing_in_a_bits_source;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25]
  assign auto_control_xing_in_d_bits_data = {31'h0, _GEN[auto_control_xing_in_a_bits_address[6:3]] ? _GEN_0[auto_control_xing_in_a_bits_address[6:3]] : 33'h0};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  assign auto_io_out_pins_0_o_oval = portReg ^ xorReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :74:24, :106:26, :231:43]
  assign auto_io_out_pins_0_o_oe = _oeReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :76:22]
  assign auto_io_out_pins_0_o_ie = _ieReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :79:22]
  assign auto_io_out_pins_0_o_pue = _pueReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :77:22]
  assign auto_io_out_pins_0_o_ds = dsReg_0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :78:23]
  assign auto_io_out_pins_0_o_ds1 = dsReg_0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:67:25, :78:23]
endmodule

