// Generated by CIRCT firtool-1.75.0
module TLInterconnectCoupler_pbus_to_device_named_uart_0(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         auto_control_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_control_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_control_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_control_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_control_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [30:0] auto_control_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_control_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_control_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_control_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_control_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_control_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_control_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_control_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_control_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_tl_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [30:0] auto_tl_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_tl_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_tl_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_tl_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_tl_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  TLFragmenter_UART fragmenter (	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .clock                        (clock),
    .reset                        (reset),
    .auto_anon_in_a_ready         (auto_tl_in_a_ready),
    .auto_anon_in_a_valid         (auto_tl_in_a_valid),
    .auto_anon_in_a_bits_opcode   (auto_tl_in_a_bits_opcode),
    .auto_anon_in_a_bits_size     (auto_tl_in_a_bits_size),
    .auto_anon_in_a_bits_source   (auto_tl_in_a_bits_source),
    .auto_anon_in_a_bits_address  (auto_tl_in_a_bits_address),
    .auto_anon_in_a_bits_mask     (auto_tl_in_a_bits_mask),
    .auto_anon_in_a_bits_data     (auto_tl_in_a_bits_data),
    .auto_anon_in_d_ready         (auto_tl_in_d_ready),
    .auto_anon_in_d_valid         (auto_tl_in_d_valid),
    .auto_anon_in_d_bits_opcode   (auto_tl_in_d_bits_opcode),
    .auto_anon_in_d_bits_size     (auto_tl_in_d_bits_size),
    .auto_anon_in_d_bits_source   (auto_tl_in_d_bits_source),
    .auto_anon_in_d_bits_data     (auto_tl_in_d_bits_data),
    .auto_anon_out_a_ready        (auto_control_xing_out_a_ready),
    .auto_anon_out_a_valid        (auto_control_xing_out_a_valid),
    .auto_anon_out_a_bits_opcode  (auto_control_xing_out_a_bits_opcode),
    .auto_anon_out_a_bits_size    (auto_control_xing_out_a_bits_size),
    .auto_anon_out_a_bits_source  (auto_control_xing_out_a_bits_source),
    .auto_anon_out_a_bits_address (auto_control_xing_out_a_bits_address),
    .auto_anon_out_a_bits_mask    (auto_control_xing_out_a_bits_mask),
    .auto_anon_out_a_bits_data    (auto_control_xing_out_a_bits_data),
    .auto_anon_out_d_ready        (auto_control_xing_out_d_ready),
    .auto_anon_out_d_valid        (auto_control_xing_out_d_valid),
    .auto_anon_out_d_bits_opcode  (auto_control_xing_out_d_bits_opcode),
    .auto_anon_out_d_bits_size    (auto_control_xing_out_d_bits_size),
    .auto_anon_out_d_bits_source  (auto_control_xing_out_d_bits_source),
    .auto_anon_out_d_bits_data    (auto_control_xing_out_d_bits_data)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
endmodule

