#!/usr/bin/env bash

CEVA_MEMORY_CURRENT_MODE="reserved-memory+opensbi-boot-owner"
CEVA_MEMORY_TARGET_MODE="reserved-memory+opensbi-boot-owner"
CEVA_MEMORY_ROLLBACK_MODE="return-to-debug-bootstrap-fallback"
CEVA_RESERVED_MEMORY_TRANSFER_POLICY="OPENSBI_BOOT_OWNER_ACTIVE"
CEVA_RESERVED_MEMORY_TRANSFER_TARGET="DT_RESERVED_MEMORY_PLUS_OPENSBI_VALIDATE_MARKER"
CEVA_RESERVED_MEMORY_BOOT_OWNER_TARGET="OPENSBI"
CEVA_RESERVED_MEMORY_DTB_NODE="${CEVA_RESERVED_MEMORY_DTB_NODE:-ceva_runtime_reserved}"
CEVA_RESERVED_MEMORY_DTB_COMPAT="${CEVA_RESERVED_MEMORY_DTB_COMPAT:-shared-dma-pool}"
CEVA_RESERVED_MEMORY_REUSABLE="${CEVA_RESERVED_MEMORY_REUSABLE:-0}"
CEVA_RESERVED_MEMORY_NO_MAP="${CEVA_RESERVED_MEMORY_NO_MAP:-1}"
CEVA_RESERVED_MEMORY_TRANSFER_ACTIVE="1"
CEVA_OPENSBI_CARVEOUT_POLICY="${CEVA_OPENSBI_CARVEOUT_POLICY:-LINUX_NO_MAP_OWNS_RESERVED_RANGE}"
CEVA_OPENSBI_CARVEOUT_FLAGS="${CEVA_OPENSBI_CARVEOUT_FLAGS:-NONE_VALIDATE_AND_MARKER_ONLY}"
CEVA_OPENSBI_CARVEOUT_ACTIVE="${CEVA_OPENSBI_CARVEOUT_ACTIVE:-0}"

CEVA_SIDECAR_MARKER_START=0x8FBE0000
CEVA_SIDECAR_MARKER_END=0x8FBE0FFF
CEVA_SIDECAR_IMAGE_START=0x8FBF0000
CEVA_SIDECAR_IMAGE_END=0x8FBFFFFF
CEVA_VENDOR_IMAGE_START=0x8FC00000
CEVA_VENDOR_IMAGE_END=0x8FDFFFFF
CEVA_PROOF_IMAGE_START=0x8FE00000
CEVA_PROOF_IMAGE_END=0x8FEFFFFF
CEVA_RUNTIME_RESERVED_START=0x8FBE0000
CEVA_RUNTIME_RESERVED_END=0x8FEFFFFF
CEVA_RUNTIME_RESERVED_SIZE=0x00320000

CEVA_MEMORY_REGIONS=(
  "OpenSBI:0x80000000:0x80020DE8"
  "LinuxImage:0x80200000:0x830D4808"
  "FuturePayloadInitramfs:0x83000000:0x86FFFFFF"
  "DTB:0x84000000:0x8401FFFF"
  "FrontChain:0x88000000:0x883FFFFF"
  "LegacyStageP3BD:0x8F000000:0x8F0000D8"
)