#!/usr/bin/env bash

CEVA_RUNTIME_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CEVA_RUNTIME_MEMORY_CONTRACT="${CEVA_RUNTIME_ROOT_DIR}/scripts/ceva_reserved_memory_contract.sh"

if [[ -f "$CEVA_RUNTIME_MEMORY_CONTRACT" ]]; then
	# shellcheck disable=SC1090
	source "$CEVA_RUNTIME_MEMORY_CONTRACT"
fi

CEVA_RUNTIME_CFG="${CEVA_RUNTIME_CFG:-RocketZCU104Phase0bConfig}"
CEVA_RUNTIME_LAUNCH_MODE="opensbi-owned-runtime-with-gdb-bootstrap"
CEVA_RUNTIME_PRODUCTION_OWNER="opensbi"
CEVA_RUNTIME_MANIFEST_PURPOSE="production-launch-interface"
CEVA_RUNTIME_BOOT_STAGE="pre-linux-opensbi"
CEVA_RUNTIME_LAUNCH_OWNER_CURRENT="OPENSBI"
CEVA_RUNTIME_LAUNCH_OWNER_TARGET="OPENSBI"
CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_CURRENT="GDB"
CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_ROLE="DEBUG_FALLBACK_ONLY"
CEVA_RUNTIME_STAGING_OWNER="OPENSBI"
CEVA_RUNTIME_STAGING_CONSUMER="OPENSBI_RESERVED_STAGING"
CEVA_RUNTIME_STAGING_ACTIVE="1"
CEVA_RUNTIME_BOOT_OWNER_METADATA_VERSION="1"
CEVA_RUNTIME_BOOT_OWNER_CLEAR_MARKER_POLICY="CLEAR_BEFORE_LOAD"
CEVA_RUNTIME_BOOT_OWNER_STAGE_ORDER="MARKER,SIDECAR,VENDOR,PROOF"
CEVA_RUNTIME_BOOT_OWNER_LINUX_HANDOFF_POLICY="CONTINUE_WITHOUT_RUNTIME_START"
CEVA_RUNTIME_BOOT_OWNER_SIDECAR_START_POLICY="DEFERRED_UNTIL_OWNER_TRANSFER"
CEVA_RUNTIME_BOOT_OWNER_REQUIRED_READY_MARKER="SIDECAR_INGRESS_READY"

CEVA_RUNTIME_BITSTREAM="${CEVA_RUNTIME_ROOT_DIR}/generated-src/chipyard.fpga.zcu104.ZCU104FPGATestHarness.${CEVA_RUNTIME_CFG}/obj/ZCU104FPGATestHarness.bit"
CEVA_RUNTIME_PAYLOAD_BIN="${CEVA_RUNTIME_ROOT_DIR}/linux-bringup/payload/fw_payload.bin"
CEVA_RUNTIME_DTB="${CEVA_RUNTIME_ROOT_DIR}/linux-bringup/dtb/chipyard-zcu104-fedora.dtb"
CEVA_RUNTIME_SDBOOT_BIN="${CEVA_RUNTIME_ROOT_DIR}/src/main/resources/zcu104/sdboot/build/sdboot.bin"
CEVA_RUNTIME_MANIFEST_PATH="${CEVA_RUNTIME_ROOT_DIR}/linux-bringup/payload/ceva_runtime_launch_manifest.env"
CEVA_RUNTIME_GDB_BIN="${CEVA_RUNTIME_GDB_BIN:-/root/chipyard/.oclaw-env/riscv-tools/bin/riscv64-unknown-elf-gdb}"
CEVA_RUNTIME_PROGRAM_BIT_SCRIPT="${CEVA_RUNTIME_ROOT_DIR}/scripts/program_phase0b_bit.sh"
CEVA_RUNTIME_JLINK_GUARD_SCRIPT="${CEVA_RUNTIME_ROOT_DIR}/scripts/jlink_guard.sh"
CEVA_RUNTIME_PHASE2_LAUNCH_GDB="${CEVA_RUNTIME_ROOT_DIR}/scripts/linux_boot_phase2_launch.gdb"
CEVA_RUNTIME_PHASE2_CAPTURE_GDB="${CEVA_RUNTIME_ROOT_DIR}/scripts/linux_boot_phase2_capture.gdb"
CEVA_RUNTIME_MANIFEST_GENERATOR="${CEVA_RUNTIME_ROOT_DIR}/scripts/generate_ceva_runtime_launch_manifest.sh"
CEVA_RUNTIME_RECOVERY_RUNBOOK="${CEVA_RUNTIME_ROOT_DIR}/docs/bringup/ceva_bt52_phase25_runbook_20260512.md"
CEVA_RUNTIME_RECOVERY_REPORT="${CEVA_RUNTIME_ROOT_DIR}/docs/bringup/phase3b_recovery_reports/phase3b_h3_recovery_20260513_001254.md"
CEVA_RUNTIME_PAYLOAD_LOAD_ADDR="${CEVA_RUNTIME_PAYLOAD_LOAD_ADDR:-0x80000000}"
CEVA_RUNTIME_DTB_LOAD_ADDR="${CEVA_RUNTIME_DTB_LOAD_ADDR:-0x84000000}"
CEVA_RUNTIME_LINUX_ENTRY_PA="${CEVA_RUNTIME_LINUX_ENTRY_PA:-0x80200000}"
CEVA_RUNTIME_LINUX_START_KERNEL_PA="${CEVA_RUNTIME_LINUX_START_KERNEL_PA:-0x80800768}"
CEVA_RUNTIME_OPENSBI_LOAD_START="${CEVA_RUNTIME_OPENSBI_LOAD_START:-0x80000000}"
CEVA_RUNTIME_OPENSBI_LOAD_END="${CEVA_RUNTIME_OPENSBI_LOAD_END:-0x80020DE8}"
CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET="${CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET:-$(printf '0x%X' "$((CEVA_RUNTIME_LINUX_ENTRY_PA - CEVA_RUNTIME_PAYLOAD_LOAD_ADDR))")}"
CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR="${CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR:-${CEVA_SIDECAR_IMAGE_START:-0x8FBF0000}}"
CEVA_RUNTIME_SIDECAR_IMAGE_MAX_SIZE="${CEVA_RUNTIME_SIDECAR_IMAGE_MAX_SIZE:-$(printf '0x%X' "$(( ${CEVA_SIDECAR_IMAGE_END:-0x8FBFFFFF} - ${CEVA_SIDECAR_IMAGE_START:-0x8FBF0000} + 1 ))")}"
CEVA_RUNTIME_SIDECAR_ENTRY_ADDR="${CEVA_RUNTIME_SIDECAR_ENTRY_ADDR:-${CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR}}"
CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR="${CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR:-${CEVA_SIDECAR_MARKER_START:-0x8FBE0000}}"
CEVA_RUNTIME_SIDECAR_MARKER_PAGE_SIZE="${CEVA_RUNTIME_SIDECAR_MARKER_PAGE_SIZE:-$(printf '0x%X' "$(( ${CEVA_SIDECAR_MARKER_END:-0x8FBE0FFF} - ${CEVA_SIDECAR_MARKER_START:-0x8FBE0000} + 1 ))")}"
CEVA_RUNTIME_SIDECAR_MARKER_WINDOW_MODE="${CEVA_RUNTIME_SIDECAR_MARKER_WINDOW_MODE:-INDEPENDENT}"
CEVA_RUNTIME_BOOT_OWNER_MARKER_ADDR="${CEVA_RUNTIME_BOOT_OWNER_MARKER_ADDR:-${CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR}}"
CEVA_RUNTIME_VENDOR_IMAGE_LOAD_ADDR="${CEVA_RUNTIME_VENDOR_IMAGE_LOAD_ADDR:-0x8FC00000}"
CEVA_RUNTIME_VENDOR_IMAGE_MAX_SIZE="${CEVA_RUNTIME_VENDOR_IMAGE_MAX_SIZE:-0x00200000}"
CEVA_RUNTIME_PROOF_IMAGE_LOAD_ADDR="${CEVA_RUNTIME_PROOF_IMAGE_LOAD_ADDR:-0x8FE00000}"
CEVA_RUNTIME_PROOF_IMAGE_MAX_SIZE="${CEVA_RUNTIME_PROOF_IMAGE_MAX_SIZE:-0x00100000}"

export CEVA_RUNTIME_ROOT_DIR
export CEVA_RUNTIME_MEMORY_CONTRACT
export CEVA_RUNTIME_CFG
export CEVA_RUNTIME_LAUNCH_MODE
export CEVA_RUNTIME_PRODUCTION_OWNER
export CEVA_RUNTIME_MANIFEST_PURPOSE
export CEVA_RUNTIME_BOOT_STAGE
export CEVA_RUNTIME_LAUNCH_OWNER_CURRENT
export CEVA_RUNTIME_LAUNCH_OWNER_TARGET
export CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_CURRENT
export CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_ROLE
export CEVA_RUNTIME_STAGING_OWNER
export CEVA_RUNTIME_STAGING_CONSUMER
export CEVA_RUNTIME_STAGING_ACTIVE
export CEVA_RUNTIME_BOOT_OWNER_METADATA_VERSION
export CEVA_RUNTIME_BOOT_OWNER_CLEAR_MARKER_POLICY
export CEVA_RUNTIME_BOOT_OWNER_STAGE_ORDER
export CEVA_RUNTIME_BOOT_OWNER_LINUX_HANDOFF_POLICY
export CEVA_RUNTIME_BOOT_OWNER_SIDECAR_START_POLICY
export CEVA_RUNTIME_BOOT_OWNER_REQUIRED_READY_MARKER
export CEVA_RUNTIME_BITSTREAM
export CEVA_RUNTIME_PAYLOAD_BIN
export CEVA_RUNTIME_DTB
export CEVA_RUNTIME_SDBOOT_BIN
export CEVA_RUNTIME_MANIFEST_PATH
export CEVA_RUNTIME_GDB_BIN
export CEVA_RUNTIME_PROGRAM_BIT_SCRIPT
export CEVA_RUNTIME_JLINK_GUARD_SCRIPT
export CEVA_RUNTIME_PHASE2_LAUNCH_GDB
export CEVA_RUNTIME_PHASE2_CAPTURE_GDB
export CEVA_RUNTIME_MANIFEST_GENERATOR
export CEVA_RUNTIME_RECOVERY_RUNBOOK
export CEVA_RUNTIME_RECOVERY_REPORT
export CEVA_RUNTIME_PAYLOAD_LOAD_ADDR
export CEVA_RUNTIME_DTB_LOAD_ADDR
export CEVA_RUNTIME_LINUX_ENTRY_PA
export CEVA_RUNTIME_LINUX_START_KERNEL_PA
export CEVA_RUNTIME_OPENSBI_LOAD_START
export CEVA_RUNTIME_OPENSBI_LOAD_END
export CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET
export CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR
export CEVA_RUNTIME_SIDECAR_IMAGE_MAX_SIZE
export CEVA_RUNTIME_SIDECAR_ENTRY_ADDR
export CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR
export CEVA_RUNTIME_SIDECAR_MARKER_PAGE_SIZE
export CEVA_RUNTIME_SIDECAR_MARKER_WINDOW_MODE
export CEVA_RUNTIME_BOOT_OWNER_MARKER_ADDR
export CEVA_RUNTIME_VENDOR_IMAGE_LOAD_ADDR
export CEVA_RUNTIME_VENDOR_IMAGE_MAX_SIZE
export CEVA_RUNTIME_PROOF_IMAGE_LOAD_ADDR
export CEVA_RUNTIME_PROOF_IMAGE_MAX_SIZE