#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAUNCH_CONTRACT="${ROOT_DIR}/scripts/ceva_runtime_launch_contract.sh"
MEMORY_CONTRACT="${ROOT_DIR}/scripts/ceva_reserved_memory_contract.sh"

source "$LAUNCH_CONTRACT"
source "$MEMORY_CONTRACT"

if (( CEVA_RUNTIME_LINUX_ENTRY_PA < CEVA_RUNTIME_PAYLOAD_LOAD_ADDR )); then
  echo "ERROR: invalid launch contract: linux entry below payload load base" >&2
  exit 1
fi

if (( CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET != (CEVA_RUNTIME_LINUX_ENTRY_PA - CEVA_RUNTIME_PAYLOAD_LOAD_ADDR) )); then
  echo "ERROR: invalid launch contract: opensbi payload offset mismatch" >&2
  exit 1
fi

OUT="${1:-${CEVA_RUNTIME_MANIFEST_PATH}}"
MANIFEST_COMMIT="$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo UNKNOWN)"
MANIFEST_BRANCH="$(git -C "$ROOT_DIR" branch --show-current 2>/dev/null || echo UNKNOWN)"

require_file() {
  local path="$1"

  if [[ ! -f "$path" ]]; then
    echo "ERROR: manifest input missing: $path" >&2
    exit 1
  fi
}

relpath() {
  local path="$1"

  if [[ "$path" == "$ROOT_DIR"/* ]]; then
    printf '%s\n' "${path#${ROOT_DIR}/}"
  else
    printf '%s\n' "$path"
  fi
}

record_artifact() {
  local prefix="$1"
  local path="$2"

  if [[ -f "$path" ]]; then
    local hash size rel
    hash="$(sha256sum "$path" | awk '{print $1}')"
    size="$(stat -c %s "$path")"
    rel="$(relpath "$path")"
    printf '%s_PATH=%s\n' "$prefix" "$rel"
    printf '%s_SHA256=%s\n' "$prefix" "$hash"
    printf '%s_SIZE=%s\n' "$prefix" "$size"
  else
    printf '%s_PATH=%s\n' "$prefix" "MISSING"
    printf '%s_SHA256=%s\n' "$prefix" "MISSING"
    printf '%s_SIZE=%s\n' "$prefix" "MISSING"
  fi
}

require_file "$CEVA_RUNTIME_BITSTREAM"
require_file "$CEVA_RUNTIME_DTB"
require_file "$CEVA_RUNTIME_SDBOOT_BIN"

mkdir -p "$(dirname "$OUT")"

{
  echo "# CEVA runtime launch manifest"
  echo "CEVA_RUNTIME_MANIFEST_VERSION=2"
  echo "CEVA_RUNTIME_MANIFEST_SOURCE_COMMIT=${MANIFEST_COMMIT}"
  echo "CEVA_RUNTIME_MANIFEST_SOURCE_BRANCH=${MANIFEST_BRANCH}"
  echo "CEVA_RUNTIME_CFG=${CEVA_RUNTIME_CFG}"
  echo "CEVA_RUNTIME_LAUNCH_MODE=${CEVA_RUNTIME_LAUNCH_MODE}"
  echo "CEVA_RUNTIME_PRODUCTION_OWNER=${CEVA_RUNTIME_PRODUCTION_OWNER}"
  echo "CEVA_RUNTIME_MANIFEST_PURPOSE=${CEVA_RUNTIME_MANIFEST_PURPOSE}"
  echo "CEVA_RUNTIME_BOOT_STAGE=${CEVA_RUNTIME_BOOT_STAGE}"
  echo "CEVA_RUNTIME_LAUNCH_OWNER_CURRENT=${CEVA_RUNTIME_LAUNCH_OWNER_CURRENT}"
  echo "CEVA_RUNTIME_LAUNCH_OWNER_TARGET=${CEVA_RUNTIME_LAUNCH_OWNER_TARGET}"
  echo "CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_CURRENT=${CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_CURRENT}"
  echo "CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_ROLE=${CEVA_RUNTIME_PAYLOAD_BOOTSTRAP_ROLE}"
  echo "CEVA_RUNTIME_STAGING_OWNER=${CEVA_RUNTIME_STAGING_OWNER}"
  echo "CEVA_RUNTIME_STAGING_CONSUMER=${CEVA_RUNTIME_STAGING_CONSUMER}"
  echo "CEVA_RUNTIME_STAGING_ACTIVE=${CEVA_RUNTIME_STAGING_ACTIVE}"
  echo "CEVA_RUNTIME_BOOT_OWNER_METADATA_VERSION=${CEVA_RUNTIME_BOOT_OWNER_METADATA_VERSION}"
  echo "CEVA_RUNTIME_BOOT_OWNER_CLEAR_MARKER_POLICY=${CEVA_RUNTIME_BOOT_OWNER_CLEAR_MARKER_POLICY}"
  echo "CEVA_RUNTIME_BOOT_OWNER_STAGE_ORDER=${CEVA_RUNTIME_BOOT_OWNER_STAGE_ORDER}"
  echo "CEVA_RUNTIME_BOOT_OWNER_LINUX_HANDOFF_POLICY=${CEVA_RUNTIME_BOOT_OWNER_LINUX_HANDOFF_POLICY}"
  echo "CEVA_RUNTIME_BOOT_OWNER_SIDECAR_START_POLICY=${CEVA_RUNTIME_BOOT_OWNER_SIDECAR_START_POLICY}"
  echo "CEVA_RUNTIME_BOOT_OWNER_REQUIRED_READY_MARKER=${CEVA_RUNTIME_BOOT_OWNER_REQUIRED_READY_MARKER}"
  echo "CEVA_RUNTIME_PAYLOAD_LOAD_ADDR=${CEVA_RUNTIME_PAYLOAD_LOAD_ADDR}"
  echo "CEVA_RUNTIME_DTB_LOAD_ADDR=${CEVA_RUNTIME_DTB_LOAD_ADDR}"
  echo "CEVA_RUNTIME_LINUX_ENTRY_PA=${CEVA_RUNTIME_LINUX_ENTRY_PA}"
  echo "CEVA_RUNTIME_LINUX_START_KERNEL_PA=${CEVA_RUNTIME_LINUX_START_KERNEL_PA}"
  echo "CEVA_RUNTIME_OPENSBI_LOAD_START=${CEVA_RUNTIME_OPENSBI_LOAD_START}"
  echo "CEVA_RUNTIME_OPENSBI_LOAD_END=${CEVA_RUNTIME_OPENSBI_LOAD_END}"
  echo "CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET=${CEVA_RUNTIME_OPENSBI_PAYLOAD_OFFSET}"
  echo "CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR=${CEVA_RUNTIME_SIDECAR_IMAGE_LOAD_ADDR}"
  echo "CEVA_RUNTIME_SIDECAR_IMAGE_MAX_SIZE=${CEVA_RUNTIME_SIDECAR_IMAGE_MAX_SIZE}"
  echo "CEVA_RUNTIME_SIDECAR_ENTRY_ADDR=${CEVA_RUNTIME_SIDECAR_ENTRY_ADDR}"
  echo "CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR=${CEVA_RUNTIME_SIDECAR_MARKER_PAGE_ADDR}"
  echo "CEVA_RUNTIME_SIDECAR_MARKER_PAGE_SIZE=${CEVA_RUNTIME_SIDECAR_MARKER_PAGE_SIZE}"
  echo "CEVA_RUNTIME_SIDECAR_MARKER_WINDOW_MODE=${CEVA_RUNTIME_SIDECAR_MARKER_WINDOW_MODE}"
  echo "CEVA_RUNTIME_BOOT_OWNER_MARKER_ADDR=${CEVA_RUNTIME_BOOT_OWNER_MARKER_ADDR}"
  echo "CEVA_RUNTIME_VENDOR_IMAGE_LOAD_ADDR=${CEVA_RUNTIME_VENDOR_IMAGE_LOAD_ADDR}"
  echo "CEVA_RUNTIME_VENDOR_IMAGE_MAX_SIZE=${CEVA_RUNTIME_VENDOR_IMAGE_MAX_SIZE}"
  echo "CEVA_RUNTIME_PROOF_IMAGE_LOAD_ADDR=${CEVA_RUNTIME_PROOF_IMAGE_LOAD_ADDR}"
  echo "CEVA_RUNTIME_PROOF_IMAGE_MAX_SIZE=${CEVA_RUNTIME_PROOF_IMAGE_MAX_SIZE}"
  echo "CEVA_MEMORY_CURRENT_MODE=${CEVA_MEMORY_CURRENT_MODE}"
  echo "CEVA_MEMORY_TARGET_MODE=${CEVA_MEMORY_TARGET_MODE}"
  echo "CEVA_SIDECAR_MARKER_START=${CEVA_SIDECAR_MARKER_START}"
  echo "CEVA_SIDECAR_MARKER_END=${CEVA_SIDECAR_MARKER_END}"
  echo "CEVA_SIDECAR_IMAGE_START=${CEVA_SIDECAR_IMAGE_START}"
  echo "CEVA_SIDECAR_IMAGE_END=${CEVA_SIDECAR_IMAGE_END}"
  echo "CEVA_RUNTIME_RECOVERY_RUNBOOK=$(relpath "$CEVA_RUNTIME_RECOVERY_RUNBOOK")"
  echo "CEVA_RUNTIME_RECOVERY_REPORT=$(relpath "$CEVA_RUNTIME_RECOVERY_REPORT")"
  record_artifact CEVA_RUNTIME_BITSTREAM "$CEVA_RUNTIME_BITSTREAM"
  record_artifact CEVA_RUNTIME_PAYLOAD_BIN "$CEVA_RUNTIME_PAYLOAD_BIN"
  record_artifact CEVA_RUNTIME_DTB "$CEVA_RUNTIME_DTB"
  record_artifact CEVA_RUNTIME_SDBOOT_BIN "$CEVA_RUNTIME_SDBOOT_BIN"
} > "$OUT"

echo "CEVA_RUNTIME_MANIFEST=$OUT"